### ISSUE TITLE
Script Error - 'Video'

### ISSUE THREAD

**Issue by Foebik** [blacktwin/JBOPS#16]
I notice I got this error tonight. Any ideas?

```
PlexPy Notifiers :: Script error:     
    Traceback (most recent call last):         
       File "C:\Scripts\md20o21ftcjdyrtpjpacsby9.py", line 11, in             
            x += kill_stream(sessionID, message, 10, n, 'tking08', 'The Lost City of Z', '163')         
       File "C:\Scripts\create_wait_kill_all.py", line 84, in kill_stream             
            if response['MediaContainer']['Video']:     
                KeyError: 'Video'
```

**Comment by blacktwin** [comment]
The session wasn't a video?

**Comment by Foebik** [comment]
Yeah it was a video. I think he was playing "The Lost City of Z" at the time.

I also just notice my niece was watching something this, Ballerina, morning and it gave this error.

```
PlexPy Notifiers :: Script error: 
    Traceback (most recent call last): 
        File "C:\Scripts\create_wait_kill_all.py", line 140, in 
            if find_sessionID(response): 
        File "C:\Scripts\create_wait_kill_all.py", line 110, in find_sessionID 
            and part['decision'] == 'transcode': 
    KeyError: 'decision'
```


Did some more digging in the logs and found two other weird errors. I notice that after the script kicked off I was getting a lot of these, not all the time but a lot.

`PlexPy Notifiers :: Script exceeded timeout limit of 40 seconds. Script killed.`

Also I found this new unique one. Couldn't figure out how it was watching or what they were watching.

```
PlexPy Notifiers :: Script error: 
    Traceback (most recent call last): 
        File "C:\Scripts\create_wait_kill_all.py", line 140, in 
            if find_sessionID(response): 
        File "C:\Scripts\create_wait_kill_all.py", line 109, in find_sessionID 
            if video['sessionKey'] == sys.argv[3] and video['Player']['state'] == 'paused' \ 
    IndexError: list index out of range
```

**Comment by blacktwin** [comment]
@Foebik 

1. For the first error. It may be that the stream had stop while the subscript was running. So the subscript was looking for a session but no session existed. I'll have to confirm this one.

2. Ballerina issue. You're using an older version of [create_wait_kill_all](https://github.com/blacktwin/JBOPS/blob/master/killstream/create_wait_kill_all.py)?

3. `Script exceeded timeout limit of 40 seconds` this is fine. The script is being killed but only after it's executed the subscript.

4. new unique one. Same as Ballerina issue. Make sure you are using the latest version.

**Comment by Foebik** [comment]
Looks like you did have a newer version so I'm trying that now. At for blush it I found these two additions in the new code. -Thanks

```
PLEXPY_APIKEY = 'xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx'  # Your PlexPy API key
PLEXPY_URL = 'http://localhost:8181/'  # Your PlexPy URL
```

**Comment by blacktwin** [comment]
Ok, so close?

**Comment by Foebik** [comment]
Just checked the logs again. Wanted it to run for a bit to catch any issues. Didn't see the errors I saw before. I will check tonight on a test account when I get home to see if it still works. It doesnt seem to work on my main account for the server, which is fine. But I imagine we will most likely be good to close.

**Comment by blacktwin** [comment]
So I've moved the create_wait_kill_all.py from killstreams to archive as some users have a collection of old subscripts in the plexpy/scripts directory. If you get a chance can you try this [script](https://gist.github.com/blacktwin/e188a7046394d2b1d2bfe8e693d306a6)? Once I get an "OK!" from others I'll add it into the killstreams section of the repo.

**Comment by Foebik** [comment]
Got these logs when running your 'new' script.

```
2017-09-30 03:28:24 | ERROR | PlexPy Notifiers :: Script error:     Traceback (most recent call last):         File "C:\Scripts\create_wait_kill_all.v2.py", line 27, in             from plexapi.server import PlexServer     ImportError: No module named plexapi.server

2017-09-30 03:28:24 | DEBUG | PlexPy Notifiers :: Executing script in a new thread.

2017-09-30 03:28:24 | DEBUG | PlexPy Notifiers :: Full script is: ['python', 'C:\\Scripts\\create_wait_kill_all.v2.py', 'jayflixtest', '192.168.1.9', '126']

2017-09-30 03:28:24 | DEBUG | PlexPy Notifiers :: Trying to run notify script, action: pause, arguments: [u'jayflixtest', u'192.168.1.9', u'126']

2017-09-30 03:28:24 | DEBUG | PlexPy ActivityHandler :: Session 126 has been paused.
```

**Comment by blacktwin** [comment]
You need to install `plexapi`.  `pip install plexapi`

**Comment by Foebik** [comment]
Installed it successfully. Still get these errors when I test.


```
Timestamp | Level | Message

2017-10-02 15:01:57 | ERROR | PlexPy Notifiers :: Script error:     Traceback (most recent call last):         File "C:\Scripts\create_wait_kill_all.v2.py", line 74, in             if session.sessionKey == int(sessionKey) and session.usernames[0] not in ignore_lst:     ValueError: invalid literal for int() with base 10: 'Melanie'

2017-10-02 15:01:56 | DEBUG | PlexPy Notifiers :: Executing script in a new thread.

2017-10-02 15:01:56 | DEBUG | PlexPy Notifiers :: Full script is: ['python', 'C:\\Scripts\\create_wait_kill_all.v2.py', 'Melanie', '192.168.1.2', '18']

2017-10-02 15:01:56 | DEBUG | PlexPy Notifiers :: Trying to run notify script, action: pause, arguments: [u'Melanie', u'192.168.1.2', u'18']

2017-10-02 15:01:55 | DEBUG | PlexPy ActivityHandler :: Session 18 has been paused.
```

**Comment by blacktwin** [comment]
oh, so your script arguments aren't matching up. This script only needs `{session_key}` but you're passing 3 arguments, probably needed for another script. So you'll need to make sure that the argument you need for this script is being called. Based on what you have in the error it looks like you have `{username} {ip_address} {session_key}` . I kinda explain the situation [here](https://www.reddit.com/r/PleX/comments/6zv3iw/how_to_setup_multiple_plexpy_scripts_that_require/dmydtd6/?st=j8anui88&sh=f8f343af). 

So for your situation you just need to change the `sys.argv[1]` to `sys.argv[3]` on [line 40](https://gist.github.com/blacktwin/e188a7046394d2b1d2bfe8e693d306a6#file-create_wait_kill_all_main-py-L40). 

```python
sessionKey = sys.argv[3]
```

**Comment by blacktwin** [comment]
@Foebik Working now?

**Comment by Foebik** [comment]
No, I've been trying to figure it out for myself. I also notice the kill_more_than script wasn't functioning last night. I don't think it is a shared variable issue. I just use the 2 scripts you made (one pause and one concurrent). Between the two they don't share any resources as I under stand it.
{user} {ip_address} and {session_key} for the other.

I thought I try and figure it out on my own. But it has been slow going.

**Comment by blacktwin** [comment]
So your script arguments in PlexPy are `{user} {ip_address} {session_key}` correct?

**Comment by Foebik** [comment]
user not username

```
PlexPy > Settings > Notifications > Script > Script Arguments      
        {user} {ip_address}
```

**Comment by blacktwin** [comment]
[`{username {ip_address}`](https://github.com/blacktwin/JBOPS/blob/master/killstream/kill_more_than.py#L16) [`{session_key}`](https://gist.github.com/blacktwin/e188a7046394d2b1d2bfe8e693d306a6#file-create_wait_kill_all_main-py-L9)

I forgot why I changed it but there was a reason.

**Comment by Foebik** [comment]
gotcha, update both scripts just in case too.

**Comment by blacktwin** [comment]
@Foebik whats the word? Got it working?

**Comment by Foebik** [comment]
Sorry testing has been slower since I loaned out my Ruko I was testing with and my wife uses the other device. I havent really seen it work. But I havent really seen any errors either.
