### ISSUE TITLE
Script erroring out on QNAP - undefined symbol: PyUnicodeUCS2_FromFormat 

### ISSUE THREAD

**Issue by andpoi** [blacktwin/JBOPS#173]
Error Below

Tautulli Notifiers :: Script error:
    Traceback (most recent call last):
        File "/share/CE_CACHEDEV1_DATA/appdata/plexpy/limiterr.py", line 46, in <module>
            import requests
        File "/share/CE_CACHEDEV1_DATA/.qpkg/Tautulli/tautulli/lib/requests/__init__.py", line 43, in <module>
            import urllib3
        File "/share/CE_CACHEDEV1_DATA/.qpkg/Tautulli/tautulli/lib/urllib3/__init__.py", line 8, in <module>
            from .connectionpool import (
        File "/share/CE_CACHEDEV1_DATA/.qpkg/Tautulli/tautulli/lib/urllib3/connectionpool.py", line 3, in <module>
            import logging
        File "/share/CE_CACHEDEV1_DATA/.qpkg/Tautulli/lib/python2.7/logging/__init__.py", line 26, in <module>
            import sys, os, time, cStringIO, traceback, warnings, weakref, collections
    ImportError: /share/CE_CACHEDEV1_DATA/.qpkg/Tautulli/lib/python2.7/lib-dynload/time.so: undefined symbol: PyUnicodeUCS2_FromFormat

**Comment by andpoi** [comment]
Looks to be the same error here: https://forum.qnap.com/viewtopic.php?p=715096&sid=dcfe9301cf571f7e69037f7b3e5487b1

**Comment by blacktwin** [comment]
Looks like the same user posted [here](https://forums.plex.tv/t/jbops-just-a-bunch-of-plex-scripts/208680/159) too. I don't use QNAP so I have no way of testing. It seems like it has something to do with QNAP's packaging or use of python. You may want to contribute to the discussion you posted to try to find your answer. 

If you'd like me to leave this open for you to provide a solution for others, I can. If not or due to lack of response I'll close this issue.

**Comment by Arcanemagus** [comment]
If your machine supports running Docker images you can also move to our [official image](https://hub.docker.com/r/tautulli/tautulli/), which should work around the issues with the main QNAP OS.

**Comment by andpoi** [comment]
@Arcanemagus thanks for the suggestion. I've moved everything over to docker. Don't have time to mess with the qnap python libraries

**Comment by blacktwin** [comment]
Thanks @Arcanemagus
