### ISSUE TITLE
Error on Weekly Stats Reporting

### ISSUE THREAD

**Issue by elit3ge** [blacktwin/JBOPS#19]
https://github.com/blacktwin/JBOPS/blob/master/reporting/weekly_stats_reporting.py

When ran from cmd or from plexpy, results in this error.

```PlexPy Notifiers :: Script error: 
    PlexPy API 'get_library_media_info' request failed: 'total_file_size'.Traceback (most recent call last): 
        File "/config/scripts/weekly_stats_reporting.py", line 294, in 
            main() 
        File "/config/scripts/weekly_stats_reporting.py", line 279, in main 
            lib_stats, user_stats_lst = get_server_stats(dates_range_lst) 
        File "/config/scripts/weekly_stats_reporting.py", line 200, in get_server_stats 
            total_size += lib_size 
    TypeError: unsupported operand type(s) for +=: 'int' and 'NoneType'
```

**Comment by blacktwin** [comment]
@elit3ge Uncomment line [121 ](https://github.com/blacktwin/JBOPS/blob/master/reporting/weekly_stats_reporting.py#L121). This will print the what's found when using `get_get_library_media_info`. What does it say?

**Comment by elit3ge** [comment]
Above goes for a while, this is the end.

```        {
            "added_at": "1269512029",
            "audio_channels": "",
            "audio_codec": "",
            "bitrate": "",
            "container": "",
            "file_size": "",
            "grandparent_rating_key": "",
            "last_played": 1494719364,
            "media_index": "1",
            "media_type": "artist",
            "parent_media_index": "",
            "parent_rating_key": "",
            "play_count": 8,
            "rating_key": "39825",
            "section_id": 4,
            "section_type": "artist",
            "thumb": "/library/metadata/39825/thumb/1499448613",
            "title": "Vampire Weekend",
            "video_codec": "",
            "video_framerate": "",
            "video_resolution": "",
            "year": ""
        }
    ],
    "draw": 1,
    "filtered_file_size": 0,
    "recordsFiltered": 554,
    "recordsTotal": 554,
    "total_file_size": 0
}
{
    "data": "null",
    "draw": 0,
    "error": "Unable to execute database query.",
    "recordsFiltered": 0,
    "recordsTotal": 0
}
PlexPy API 'get_library_media_info' request failed: 'total_file_size'.Traceback (most recent call last):
  File "weekly_stats_reporting.py", line 294, in <module>
    main()
  File "weekly_stats_reporting.py", line 279, in main
    lib_stats, user_stats_lst = get_server_stats(dates_range_lst)
  File "weekly_stats_reporting.py", line 200, in get_server_stats
    total_size += lib_size
TypeError: unsupported operand type(s) for +=: 'long' and 'NoneType'```

**Comment by elit3ge** [comment]
Sorted it, I had an empty library not appearing in PlexPy.
