### ISSUE TITLE
kill_stream.py script error

### ISSUE THREAD

**Issue by Palshee** [blacktwin/JBOPS#229]
Hello,
I am trying to setup kill_stream.py to do a simple kill stream where username ='username' as a test. I am running into a script error
```
2020-07-01 19:08:02 - ERROR :: Thread-30 : Tautulli Notifiers :: Script error:
  Traceback (most recent call last):
    File "/config/scripts/kill_stream.py", line 591, in <module>
      opts = parser.parse_args()
    File "/app/lib/argparse.py", line 1725, in parse_args
      args, argv = self.parse_known_args(args, namespace)
    File "/app/lib/argparse.py", line 1754, in parse_known_args
      namespace, args = self._parse_known_args(args, namespace)
    File "/app/lib/argparse.py", line 1960, in _parse_known_args
      start_index = consume_optional(start_index)
    File "/app/lib/argparse.py", line 1900, in consume_optional
      take_action(action, args, option_string)
    File "/app/lib/argparse.py", line 1812, in take_action
      argument_values = self._get_values(action, argument_strings)
    File "/app/lib/argparse.py", line 2263, in _get_values
      value = [self._get_value(action, v) for v in arg_strings]
    File "/app/lib/argparse.py", line 2263, in <listcomp>
      value = [self._get_value(action, v) for v in arg_strings]
    File "/app/lib/argparse.py", line 2278, in _get_value
      result = type_func(arg_string)
    File "/config/scripts/kill_stream.py", line 105, in arg_decoding
      return arg.decode(TAUTULLI_ENCODING).encode('UTF-8')
  AttributeError: 'str' object has no attribute 'decode'
```

**Comment by blacktwin** [comment]
I'm assuming your using the python3 version of Tautulli? A compatible version for python 3 is [here](https://github.com/blacktwin/JBOPS/tree/python3/killstream).

**Comment by Palshee** [comment]
That was it...
Thank you for being so kind to this noob.

**Comment by magefesa** [comment]
I ve updated the script to v3 compatibility but now the log says:

**2020-08-29 14:58:05 | DEBUG | Tautulli Notifiers :: Subprocess returned with status code -9.**
-- | -- | --
2020-08-29 14:58:05 | WARNING | Tautulli Notifiers :: Script exceeded timeout limit of 5 seconds. Script killed.
2020-08-29 14:58:01 | INFO | Tautulli Notifiers :: Webhook notification sent.
2020-08-29 14:58:00 | DEBUG | Tautulli Notifiers :: Executing script in a new thread.


Any help please ?
Thanks !

**Comment by arsaboo** [comment]
The python 3 link is not working and I am still getting the same error.

**Comment by blacktwin** [comment]
@arsaboo 36aa2dd3a315355bf0adfdcd7c65bbddc3a38d2f. Branch page is dead because branch was merged and deleted. Just download from master.

**Comment by arsaboo** [comment]
@blacktwin That is what I am doing. I have copied the latest files, but I am still getting the same error
