### ISSUE TITLE
Script error since tautulli 2.5.2.  Script notification sent but never receved by client

### ISSUE THREAD

**Issue by Cadkey** [blacktwin/JBOPS#230]
Since v2.5.2, i have this killstream error when test on transcoding session.
transcode is detected but client don't receive message on screen

Tautulli Notifiers :: Script error:
    Traceback (most recent call last):
        File "/config/script/kill_stream.py", line 591, in <module>
            opts = parser.parse_args()
        File "/app/lib/argparse.py", line 1725, in parse_args
            args, argv = self.parse_known_args(args, namespace)
        File "/app/lib/argparse.py", line 1754, in parse_known_args
            namespace, args = self._parse_known_args(args, namespace)
        File "/app/lib/argparse.py", line 1960, in _parse_known_args
            start_index = consume_optional(start_index)
        File "/app/lib/argparse.py", line 1900, in consume_optional
            take_action(action, args, option_string)
        File "/app/lib/argparse.py", line 1812, in take_action
            argument_values = self._get_values(action, argument_strings)
        File "/app/lib/argparse.py", line 2249, in _get_values
            value = self._get_value(action, arg_string)
        File "/app/lib/argparse.py", line 2278, in _get_value
            result = type_func(arg_string)
        File "/config/script/kill_stream.py", line 105, in arg_decoding
            return arg.decode(TAUTULLI_ENCODING).encode('UTF-8')
    AttributeError: 'str' object has no attribute 'decode'

**Comment by blacktwin** [comment]
See #229

**Comment by Cadkey** [comment]
Thank you,
but now another error:
Tautulli NotificationHandler :: Unable to parse custom script arguments: No closing quotation. Using fallback.
Traceback (most recent call last):
    File "/app/plexpy/notification_handler.py", line 1181, in build_notify_text
        script_args = [str_formatter(arg) for arg in helpers.split_args(subject)]
    File "/app/plexpy/helpers.py", line 1094, in split_args
        args = shlex.split(args)
    File "/usr/local/lib/python3.8/shlex.py", line 311, in split
        return list(lex)
    File "/usr/local/lib/python3.8/shlex.py", line 300, in __next__
        token = self.get_token()
    File "/usr/local/lib/python3.8/shlex.py", line 109, in get_token
        raw = self.read_token()
    File "/usr/local/lib/python3.8/shlex.py", line 191, in read_token
        raise ValueError("No closing quotation")
ValueError: No closing quotation

**Comment by blacktwin** [comment]
Without your logs I have to guess that your kill message either has 3 single quotations or just 1 single quotation.

**Comment by Cadkey** [comment]
Yes, sorry.
mismatch between ' and ʹ
thank for your help
killstream is perfect for monitoring access to Plex
