### ISSUE TITLE
kill streams Issue

### ISSUE THREAD

**Issue by jwiese997** [blacktwin/JBOPS#233]
I'm not sure when it started happening but Tautulli is no longer killing anything that it used to using the kill_stream.py

Here's the error in the log:
Tautulli Notifiers :: Script error:
    Traceback (most recent call last):
        File "/config/scripts/kill_stream.py", line 591, in <module>
            opts = parser.parse_args()
        File "/app/tautulli/lib/argparse.py", line 1725, in parse_args
            args, argv = self.parse_known_args(args, namespace)
        File "/app/tautulli/lib/argparse.py", line 1754, in parse_known_args
            namespace, args = self._parse_known_args(args, namespace)
        File "/app/tautulli/lib/argparse.py", line 1960, in _parse_known_args
            start_index = consume_optional(start_index)
        File "/app/tautulli/lib/argparse.py", line 1900, in consume_optional
            take_action(action, args, option_string)
        File "/app/tautulli/lib/argparse.py", line 1812, in take_action
            argument_values = self._get_values(action, argument_strings)
        File "/app/tautulli/lib/argparse.py", line 2263, in _get_values
            value = [self._get_value(action, v) for v in arg_strings]
        File "/app/tautulli/lib/argparse.py", line 2263, in <listcomp>
            value = [self._get_value(action, v) for v in arg_strings]
        File "/app/tautulli/lib/argparse.py", line 2278, in _get_value
            result = type_func(arg_string)
        File "/config/scripts/kill_stream.py", line 105, in arg_decoding
            return arg.decode(TAUTULLI_ENCODING).encode('UTF-8')
    AttributeError: 'str' object has no attribute 'decode'

I'm using Tautulli in a docker on Unraid 6.9 b25

**Comment by blacktwin** [comment]
Use the version in the python3 branch.
