### ISSUE TITLE
refresh_next_episode.py errror running from Tautulli/Plex in separate containers

### ISSUE THREAD

**Issue by ookla-ariel-ride** [blacktwin/JBOPS#235]
**Describe the bug**
Trying to use refresh_next_episode.py from Tautulli (linuxserver.io latest container) to Plex (plexinc PMS docker-beta) and getting the following error:

Tautulli Notifiers :: Script error:
    Traceback (most recent call last):
        File "/scripts/refresh_next_episode.py", line 30, in <module>
            PLEX_URL = CONFIG.data['auth'].get('server_baseurl', PLEX_URL)
    KeyError: 'auth'

https://github.com/blacktwin/JBOPS/blob/master/utility/refresh_next_episode.pyb

**To Reproduce**
Followed the instructions in script to setup in Tautulli, configured PLEX_TOKEN to a valid token (successfully tested in another script).  Changed PLEX_URL to almost everything I can think of.  usually the docker name is sufficient (http://plex:32400), but I tried http://localhost:32400, http://ip_address:32400, http://docker_ip_addr:32400, etc. etc. etc.

**Desktop (please complete the following information):**
 - Ubuntu 18.04 host OS, linuxserver.io Tautuilli container, Plexinc PMS-beta container (all updated)
 - Chrome
 - Python Version 3.6.9

**Additional context**
I have many other scripts that work successfully that interact with Plex, but none that originate from another container next to my Plex container.  All the scripts so far have run from the host OS and interacted with Plex running in docker.  this is my first attempt at running a script hosted in a docker container and trying to auth with Plex running in another docker container.

I feel I am missing something obvious, but have tried everything I can think of to make this work - but always with the same results.

**Comment by blacktwin** [comment]
Just remove lines [27-28](https://github.com/blacktwin/JBOPS/blob/master/utility/refresh_next_episode.py#L27-L28). It's looking for the config.ini and it either isn't setup or can't be found.

**Comment by ookla-ariel-ride** [comment]
that fixed it.  thanks!

**Comment by rowdya22** [comment]
I've got a similar setup and problem. I've tried removing the lines indicated but that didn't work for me. I've also manually set the URL and token in the py file, fetched them automatically from /settings#tabs_tabs-plex_media_server page, and added them to the config.ini file. 

Anything else I could try?

https://hastebin.com/share/ukotehaxen.sql
```
2024-07-21 16:00:47	DEBUG	Tautulli ActivityHandler :: Session 357 paused.
2024-07-21 16:00:37	INFO	Tautulli Notifiers :: Script notification sent.
2024-07-21 16:00:37	ERROR	Tautulli Notifiers :: Script error:
    Traceback (most recent call last):
        File "/config/JBOPS/utility/refresh_next_episode.py", line 28, in <module>
            PLEX_URL = CONFIG.data['auth'].get('server_baseurl', PLEX_URL)
                                  ~~~~~~~~~~~^^^^^^^^
    KeyError: 'auth'
2024-07-21 16:00:37	DEBUG	Tautulli Notifiers :: Subprocess returned with status code 1.
2024-07-21 16:00:36	DEBUG	Tautulli Notifiers :: Executing script in a new thread.
2024-07-21 16:00:36	DEBUG	Tautulli Notifiers :: Full script is: ['/lsiopy/bin/python3', '/config/JBOPS/utility/refresh_next_episode.py', 'Bluey', '44', '00']
2024-07-21 16:00:36	DEBUG	Tautulli Notifiers :: Trying to run notify script: /config/JBOPS/utility/refresh_next_episode.py, arguments: ['Bluey', '44', '00'], action: watched
2024-07-21 16:00:36	INFO	Tautulli NotificationHandler :: Preparing notification for notifier_id 7.

```
