### ISSUE TITLE
Kill Stream won't work and comes with error 1Issue

### ISSUE THREAD

**Issue by BiG2596BoSS** [blacktwin/JBOPS#242]
Hi 

I'm Trying to use the script to kill any 4K Transcoding but it wouldn't work

`

2020-09-13 01:21:32 | ERROR | Tautulli Notifiers :: Script error:    Traceback (most recent call last):        File "/opt/tautulli/JBOPS-master/killstream/kill_stream.py", line 591, in <module>            opts = parser.parse_args()        File "/opt/tautulli/lib/argparse.py", line 1725, in parse_args            args, argv = self.parse_known_args(args, namespace)        File "/opt/tautulli/lib/argparse.py", line 1754, in parse_known_args            namespace, args = self._parse_known_args(args, namespace)        File "/opt/tautulli/lib/argparse.py", line 1960, in _parse_known_args            start_index = consume_optional(start_index)        File "/opt/tautulli/lib/argparse.py", line 1900, in consume_optional            take_action(action, args, option_string)        File "/opt/tautulli/lib/argparse.py", line 1812, in take_action            argument_values = self._get_values(action, argument_strings)        File "/opt/tautulli/lib/argparse.py", line 2249, in _get_values            value = self._get_value(action, arg_string)        File "/opt/tautulli/lib/argparse.py", line 2278, in _get_value            result = type_func(arg_string)        File "/opt/tautulli/JBOPS-master/killstream/kill_stream.py", line 105, in arg_decoding            return arg.decode(TAUTULLI_ENCODING).encode('UTF-8')    AttributeError: 'str' object has no attribute 'decode'
-- | -- | --
2020-09-13 01:21:32 | DEBUG | Tautulli Notifiers :: Subprocess returned with status code 1.
2020-09-13 01:21:32 | DEBUG | Tautulli Notifiers :: Executing script in a new thread.

`

This is the log showing the error

**Comment by rssnyder** [comment]
What was the solution for this?
