### ISSUE TITLE
Error with create_wait_kill_all.py

### ISSUE THREAD

**Issue by christronyxyocum** [blacktwin/JBOPS#25]
Running latest version of Plex, PlexPy and the create_wait_kill_all.py script. Seeing the following error:

`PlexPy Notifiers :: Script error:
    Traceback (most recent call last):
        File "/app/plexpy/scripts/create_wait_kill_all.py", line 152, in
            if find_sessionID(response):
        File "/app/plexpy/scripts/create_wait_kill_all.py", line 122, in find_sessionID
            for s in response['MediaContainer']['Video']:
    KeyError: 'Video'`

**Comment by christronyxyocum** [comment]
Seeing this one too, but almost every time the script kicks off:

`PlexPy Notifiers :: Script error:
    Traceback (most recent call last):
        File "/app/plexpy/scripts/create_wait_kill_all.py", line 152, in
            if find_sessionID(response):
        File "/app/plexpy/scripts/create_wait_kill_all.py", line 123, in find_sessionID
            if s['sessionKey'] == sys.argv[1]:
    IndexError: list index out of range`

**Comment by blacktwin** [comment]
Can you try these two instead?
https://github.com/blacktwin/JBOPS/blob/master/killstream/wait_kill_pause_notify_main.py
https://github.com/blacktwin/JBOPS/blob/master/killstream/wait_kill_pause_notify_sub.py

**Comment by christronyxyocum** [comment]
Will give them a shot and let you know. Thanks!

**Comment by christronyxyocum** [comment]
Pretty sure I put in all the settings correct, but I'm seeing the following error:

`PlexPy Notifiers :: Script error: 
    Traceback (most recent call last): 
        File "/app/plexpy/scripts/wait_kill_pause_notify_main.py", line 25, in 
            from plexapi.server import PlexServer 
    ImportError: No module named plexapi.server`

**Comment by christronyxyocum** [comment]
Ok, still getting the following:

`PlexPy Notifiers :: Script error: 
    Traceback (most recent call last): 
        File "/app/plexpy/scripts/wait_kill_pause_notify_main.py", line 56, in 
            sessionKey = sys.argv[1] 
    IndexError: list index out of range`

**Comment by blacktwin** [comment]
can you provide more of the logs? 

Something like:
```
2017-10-25 20:31:51 | DEBUG | PlexPy Notifiers :: Full script is: ['python', 'C:\\JBOPS\\killstream\\wait_kill_pause_notify_main.py', '7']
2017-10-25 20:31:51 | DEBUG | PlexPy Notifiers :: Trying to run notify script, action: pause, arguments: [u'7']
2017-10-25 20:31:50 | DEBUG | PlexPy Monitor :: Session 7 has been paused.
```

**Comment by christronyxyocum** [comment]
Here are more logs:

`

2017-11-01 11:05:26 | ERROR | PlexPy Notifiers :: Script error:     Traceback (most recent call last):         File "/app/plexpy/scripts/wait_kill_pause_notify_main.py", line 56, in             sessionKey = sys.argv[1]     IndexError: list index out of range
-- | -- | --
2017-11-01 11:05:26 | DEBUG | PlexPy Notifiers :: Executing script in a new thread.
2017-11-01 11:05:26 | DEBUG | PlexPy Notifiers :: Full script is: ['python', u'/app/plexpy/scripts/wait_kill_pause_notify_main.py']
2017-11-01 11:05:26 | DEBUG | PlexPy Notifiers :: Trying to run notify script, action: pause, arguments: None`

Could it be that it didn't set any args? Oh wait, I don't think I set the {session_key} arg in PlexPy....

`facepalm`

I'll test it again....

**Comment by christronyxyocum** [comment]
Ok, wound up with:

`PlexPy Notifiers :: Script error:
        File "/config/scripts/wait_kill_pause_notify_sub.py", line 35
            print('Error: {}'.format(e))
                    ^
    IndentationError: expected an indented block `

So I indented line 35 (last line) and now it seems to work. Waiting to see if it kills the stream.

**Comment by christronyxyocum** [comment]
Didn't work. The pyc script it creates is full of weird characters. Not sure if this is a permissions issue or what, but there isn't anything in the logs.

**Comment by christronyxyocum** [comment]
I just need to stop working on this stuff when I'm tired. It works.
