### ISSUE TITLE
kill_stream not working

### ISSUE THREAD

**Issue by arsaboo** [blacktwin/JBOPS#266]
I am running Tautulli in a docker that is recently updated. However, I am not able to get kill_stream working. 
I get the following error. I have updated all the files from the repo.
```
Tautulli Notifiers :: Script error:
    Traceback (most recent call last):
        File "/config/scripts/kill_stream.py", line 591, in <module>
            opts = parser.parse_args()
        File "/app/tautulli/lib/argparse.py", line 1725, in parse_args
            args, argv = self.parse_known_args(args, namespace)
        File "/app/tautulli/lib/argparse.py", line 1754, in parse_known_args
            namespace, args = self._parse_known_args(args, namespace)
        File "/app/tautulli/lib/argparse.py", line 1960, in _parse_known_args
            start_index = consume_optional(start_index)
        File "/app/tautulli/lib/argparse.py", line 1900, in consume_optional
            take_action(action, args, option_string)
        File "/app/tautulli/lib/argparse.py", line 1812, in take_action
            argument_values = self._get_values(action, argument_strings)
        File "/app/tautulli/lib/argparse.py", line 2249, in _get_values
            value = self._get_value(action, arg_string)
        File "/app/tautulli/lib/argparse.py", line 2278, in _get_value
            result = type_func(arg_string)
        File "/config/scripts/kill_stream.py", line 105, in arg_decoding
            return arg.decode(TAUTULLI_ENCODING).encode('UTF-8')
    AttributeError: 'str' object has no attribute 'decode'
```
I saw other bug reports similar to this that directed to python 3 version, but it looks like it was merged in the master branch, which I am using currently.

**Comment by arsaboo** [comment]
The other error that I see is 
```
Tautulli Notifiers :: Script error:
    usage: kill_stream.py [-h] --jbop {stream,allStreams,paused} [--userId USERID]
                                                [--username USERNAME] [--sessionId SESSIONID]
                                                [--notify NOTIFY] [--limit LIMIT] [--interval INTERVAL]
                                                [--killMessage KILLMESSAGE [KILLMESSAGE ...]]
                                                [--richMessage {discord,slack}]
                                                [--serverName SERVERNAME] [--plexUrl PLEXURL]
                                                [--posterUrl POSTERURL] [--richColor RICHCOLOR]
                                                [--debug]
    kill_stream.py: error: argument --jbop is required
```

**Comment by blacktwin** [comment]
Can you please keep the conversation in one location.
[`File "/config/scripts/kill_stream.py", line 105, in arg_decoding`](https://github.com/blacktwin/JBOPS/blob/master/killstream/kill_stream.py#L105) 

Either you haven't updated the file or you've modified the script in some way.

**Comment by arsaboo** [comment]
Apologies and thanks for your assistance. Looks like I had updated the file in the wrong location. I changed the file and now it works. Thanks!
