### ISSUE TITLE
Killstream not working after update tautulli to 2.6.4

### ISSUE THREAD

**Issue by spiiikool9** [blacktwin/JBOPS#274]
Hi! Everything worked fluidly until I have updated tautulli to 2.6.4. Now killstream doesn't work.
I'm getting this 2 errors:

Tautulli Notifiers :: Script error:
    Traceback (most recent call last):
        File "/home/winter/Tautulli_Script/kill_stream.py", line 586, in <module>
            opts = parser.parse_args()
        File "/opt/Tautulli/lib/argparse.py", line 1725, in parse_args
            args, argv = self.parse_known_args(args, namespace)
        File "/opt/Tautulli/lib/argparse.py", line 1754, in parse_known_args
            namespace, args = self._parse_known_args(args, namespace)
        File "/opt/Tautulli/lib/argparse.py", line 1960, in _parse_known_args
            start_index = consume_optional(start_index)
        File "/opt/Tautulli/lib/argparse.py", line 1900, in consume_optional
            take_action(action, args, option_string)
        File "/opt/Tautulli/lib/argparse.py", line 1812, in take_action
            argument_values = self._get_values(action, argument_strings)
        File "/opt/Tautulli/lib/argparse.py", line 2249, in _get_values
            value = self._get_value(action, arg_string)
        File "/opt/Tautulli/lib/argparse.py", line 2278, in _get_value
            result = type_func(arg_string)
        File "/home/winter/Tautulli_Script/kill_stream.py", line 102, in arg_decoding
            return arg.decode(TAUTULLI_ENCODING).encode('UTF-8')
    AttributeError: 'str' object has no attribute 'decode' 

and this:

Tautulli Notifiers :: Script error:
    usage: kill_stream.py [-h] --jbop {stream,allStreams,paused} [--userId USERID]
                                                [--username USERNAME] [--sessionId SESSIONID]
                                                [--notify NOTIFY] [--limit LIMIT] [--interval INTERVAL]
                                                [--killMessage KILLMESSAGE [KILLMESSAGE ...]]
                                                [--richMessage {discord,slack}]
                                                [--serverName SERVERNAME] [--plexUrl PLEXURL]
                                                [--posterUrl POSTERURL] [--richColor RICHCOLOR]
                                                [--debug]
    kill_stream.py: error: argument --jbop is required 

Thanks in advance!

**Comment by blacktwin** [comment]
Download the script again.

**Comment by spiiikool9** [comment]
> Download the script again.

Thanks, solved!!
