### ISSUE TITLE
Unknown filter category: unwatched when trying to sync TV Library between 2 users

### ISSUE THREAD

**Issue by merqwury** [blacktwin/JBOPS#276]
**Describe the bug**

Trying to update Watch Status from one user to another (anything besides Movies) on my Plex server gives me the following error. 

```
Traceback (most recent call last):
  File "/mnt/user/appdata/docker/tautulli/config/scripts/JBOPS/utility/sync_watch_status.py", line 504, in <module>
    watched_lst = sectionFrom.search(libtype='episode', unwatched=False)
  File "/usr/lib64/python3.9/site-packages/plexapi/library.py", line 669, in search
    args[category] = self._cleanSearchFilter(category, value, libtype)
  File "/usr/lib64/python3.9/site-packages/plexapi/library.py", line 717, in _cleanSearchFilter
    raise BadRequest('Unknown filter category: %s' % category)
plexapi.exceptions.BadRequest: Unknown filter category: unwatched
```

**Provide logs**

Tautulli logs - Nothing in the logs after clearing and running script again.

PlexAPI logs - Can't find these in my Docker container nor unRAID server.

**Link to script with bug/issue**

https://github.com/blacktwin/JBOPS/blob/master/utility/sync_watch_status.py

**To Reproduce**

Run using `python3 sync_watch_status.py --userFrom <USER1>=<SERVER> --userTo <USER2>=<SERVER> --libraries "TV"`

**Expected behavior**

Update watch status of USER2

**Desktop (please complete the following information):**
 - OS: Docker
 - Python Version 3.9.0
 - PlexAPI version 4.2.0

**Additional context**

**Comment by blacktwin** [comment]
What version of PlexAPI are you using?

**Comment by merqwury** [comment]
> 
> 
> What version of PlexAPI are you using?

Updated my OP. Using 4.2.0

**Comment by merqwury** [comment]
There also seems to be an issue with the script when running it through notification agent.

```

  | Tautulli Notifiers :: Script error:     Traceback (most recent call last):         File "/config/scripts/JBOPS/utility/sync_watch_status.py", line 537, in <module>             sync_watch_status([watched_item], watched_item.libraryName, server, username)         File "/config/scripts/JBOPS/utility/sync_watch_status.py", line 384, in sync_watch_status             sectionTo = accountTo.library.section(section)     AttributeError: 'NoneType' object has no attribute 'library'
-- | --

```

**Comment by blacktwin** [comment]
I messed up the initial PR. I'll look into the other issue too.

**Comment by merqwury** [comment]
> 
> 
> The initial issue should be resolved with that commit. Investigating the second issue.

Indeed it has. Tried and tested, however, for some reason it's not picking up everything that was watched from User1. I'll see if I find out what's the issue there.

**Comment by blacktwin** [comment]
Who is the user? Or what type of user is this for? Its failing here [`accountTo.library.section(section)`](https://github.com/blacktwin/JBOPS/blob/master/utility/sync_watch_status.py#L384) because the account you're wanting to sync watch status to was found as `None`. 

Your `'--userTo', '<USER1>=<SERVER>``  I'm assuming is redaction and not the actual values, correct?

**Comment by merqwury** [comment]
> 
> 
> Who is the user? Or what type of user is this for? Its failing here [`accountTo.library.section(section)`](https://github.com/blacktwin/JBOPS/blob/master/utility/sync_watch_status.py#L384) because the account you're wanting to sync watch status to was found as `None`.
> 
> Your `'--userTo', '=`` I'm assuming is redaction and not the actual values, correct?

It's a Home user (Managed Account available for PlexPass subscribers). Yes, I've replaced the actual Home User & Server names with `<USER1>=<SERVER>`

**Comment by blacktwin** [comment]
Is this issue only repeatable for this user or for that ratingKey? I'm not able to reproduce your issue. Something is odd about this user, as I said it's returning as `None`.

**Comment by merqwury** [comment]
> 
> 
> Is this issue only repeatable for this user or for that ratingKey? I'm not able to reproduce your issue. Something is odd about this user, as I said it's returning as `None`.

Not just that ratingKey, seems to happen for all. This is attempting to update the Watch Status from a Managed User to the Admin User. Some more extensive logs below


```
2021-01-04 22:44:23 | DEBUG | Tautulli Notifiers :: Script returned:     Connecting to admin server(s) for access info...     Request from Tautulli notification agent to update watch status     Marking watched...
-- | -- | --
2021-01-04 22:44:23 | ERROR | Tautulli Notifiers :: Script error:     Traceback (most recent call last):         File "/config/scripts/JBOPS/utility/sync_watch_status.py", line 537, in <module>             sync_watch_status([watched_item], watched_item.libraryName, server, username)         File "/config/scripts/JBOPS/utility/sync_watch_status.py", line 384, in sync_watch_status             sectionTo = accountTo.library.section(section)     AttributeError: 'NoneType' object has no attribute 'library'
2021-01-04 22:44:23 | DEBUG | Tautulli Notifiers :: Subprocess returned with status code 1.
2021-01-04 22:44:20 | DEBUG | Tautulli Notifiers :: Executing script in a new thread.
2021-01-04 22:44:20 | DEBUG | Tautulli  Notifiers :: Full script is: ['/usr/bin/python3',  '/config/scripts/JBOPS/utility/sync_watch_status.py', '--ratingKey',  '31832', '--userFrom', 'Tautulli=Tautulli', '--userTo',  'myUsername=myServer`']
2021-01-04 22:44:20 | DEBUG | Tautulli  Notifiers :: Trying to run notify script:  /config/scripts/JBOPS/utility/sync_watch_status.py, arguments:  ['--ratingKey', '31832', '--userFrom', 'Tautulli=Tautulli', '--userTo',  'myUsername=myServer`'], action: watched
```

The script arguments in Tautuli are:

`--ratingKey {rating_key} --userFrom Tautulli=Tautulli --userTo "myUsername=myServer`"`

**Comment by blacktwin** [comment]
So you good now?

**Comment by merqwury** [comment]
Yup, with https://github.com/blacktwin/JBOPS/pull/278 everything's working great.
