### ISSUE TITLE
Kill stream for 4K: issue 'utf-8' codec can't decode 

### ISSUE THREAD

**Issue by KoRnEr007** [blacktwin/JBOPS#294]
Hello,
i have tautulli on win10 and python 3.9
I try to use the script .py to kill 4K transcode but i have this error, and the transcode is not cut

`

2021-05-19 14:29:11 | DEBUG | Tautulli Notifiers :: Subprocess returned with status code 9009.
-- | -- | --
2021-05-19 14:29:11 | DEBUG | Tautulli Notifiers :: Executing script in a new thread.
2021-05-19 14:29:11 | DEBUG | Tautulli Notifiers :: Full script is: ['python', 'C:\\Users\\jon\\Downloads\\kill_stream.py']
2021-05-19 14:29:11 | DEBUG | Tautulli Notifiers :: Trying to run notify script: C:\Users\jon\Downloads\kill_stream.py, arguments: [], action: pause
2021-05-19 14:29:11 | INFO | Tautulli NotificationHandler :: Preparing notification for notifier_id 1.
2021-05-19 14:29:11 | DEBUG | Tautulli NotificationHandler :: Custom conditions evaluated to 'True'. Conditions: [True, True].
2021-05-19 14:29:11 | DEBUG | Tautulli NotificationHandler :: Condition logic [blank]: {1} and {2} &gt; True
2021-05-19 14:29:11 | DEBUG | Tautulli NotificationHandler :: {2} video_decision \| is \| 'transcode' &gt; 'transcode' &gt; True
2021-05-19 14:29:11 | DEBUG | Tautulli NotificationHandler :: {1} video_resolution \| is \| '4k' &gt; '4k' &gt; True
2021-05-19 14:29:11 | DEBUG | Tautulli NotificationHandler :: Checking custom notification conditions for notifier_id 1.
2021-05-19 14:29:11 | DEBUG | Tautulli NotificationHandler :: Global notification conditions evaluated to 'True'.
2021-05-19 14:29:11 | DEBUG | Tautulli NotificationHandler :: Checking global notification conditions.

`

Logs issue :
```
Uncaught exception: Traceback (most recent call last):
    File "plexpy\logger.py", line 405, in new_run
    File "threading.py", line 870, in run
    File "plexpy\notifiers.py", line 3095, in run_script
UnicodeDecodeError: 'utf-8' codec can't decode byte 0xe9 in position 26: invalid continuation byte
```

Rgds
jon

**Comment by josebummer** [comment]
I have the same problem, what is the solution?
