### ISSUE TITLE
plex_netflix_check.py error

### ISSUE THREAD

**Issue by kicks88** [blacktwin/JBOPS#295]
Any idea on how to fix this or tell me where I might be going wrong? Thanks

`python3 plex_netflix_check.py --l Movies --site Netflix
Running check on 2 Fast 2 Furious
Traceback (most recent call last):
  File "plex_netflix_check.py", line 230, in <module>
    main()
  File "plex_netflix_check.py", line 226, in main
    plex_library_search(opts.library[0], opts.site, opts.episodes, opts.search_limit)
  File "plex_netflix_check.py", line 176, in plex_library_search
    if instantwatch_search(title.title, title.type, site, search_limit) > 0:
  File "plex_netflix_check.py", line 80, in instantwatch_search
    res_results = res_data['div'][0]['div'][1]['div'][0]
KeyError: 1
`

**Comment by yisraelkelsick** [comment]
Also having this issue as well

**Comment by blacktwin** [comment]
Updated script. Please try again.

**Comment by kicks88** [comment]
That worked perfect cheers!
