### ISSUE TITLE
[Issue] Playlist creation with playlist manager script

### ISSUE THREAD

**Issue by irodimus** [blacktwin/JBOPS#299]
**Describe the bug**

Attempting to add or update a random playlist with filter errors with Bad Request. Using playlistmanager script https://github.com/blacktwin/JBOPS/commit/69fd40e25a835605c8e7de6bc8a88c58c2abdc82

**Provide logs**
```
Traceback (most recent call last):
  File "/Applications/Plex Scripts/Scripts/playlist_manager.py", line 906, in <module>
    create_playlist(title, keys_list, data['server'], data['user'])
  File "/Applications/Plex Scripts/Scripts/playlist_manager.py", line 601, in create_playlist
    server.createPlaylist(playlist_title, playlist_list)
  File "/usr/local/lib/python3.9/site-packages/plexapi/server.py", line 477, in createPlaylist
    return Playlist.create(
  File "/usr/local/lib/python3.9/site-packages/plexapi/playlist.py", line 384, in create
    return cls._create(server, title, items)
  File "/usr/local/lib/python3.9/site-packages/plexapi/playlist.py", line 309, in _create
    raise BadRequest('Must include items to add when creating new playlist.')
plexapi.exceptions.BadRequest: Must include items to add when creating new playlist.
```

**To Reproduce**

Tested with this:
```
python3 playlist_manager.py --jbop random --action update --name "01 Science Fiction" --libraries Movies --limit 50 --filter genre=sci-fi
```

**Expected behavior**

A playlist to be created with specified filters

**Desktop (please complete the following information):**
 - OS: Mac 10.15.7
 - Python Version: 3.9.6
 - PlexAPI version: 4.6.1

**Comment by blacktwin** [comment]
Update the script.

**Comment by irodimus** [comment]
Works great after updating, thank you!
