### ISSUE TITLE
Argparse error

### ISSUE THREAD

**Issue by lazyb0nes** [blacktwin/JBOPS#306]
When trying to kill streams the script executes but fails, the following is displayed in the tautulli logs. 

The arguments for the script are the following:
`--jbop stream --username {username} --sessionId {session_id} --killMessage 'No transcodes allowed.'`

```
Tautulli Notifiers :: Script error:
    Traceback (most recent call last):
        File "/config/scripts/kill_stream.py", line 591, in <module>
            opts = parser.parse_args()
        File "/app/tautulli/lib/argparse.py", line 1725, in parse_args
            args, argv = self.parse_known_args(args, namespace)
        File "/app/tautulli/lib/argparse.py", line 1754, in parse_known_args
            namespace, args = self._parse_known_args(args, namespace)
        File "/app/tautulli/lib/argparse.py", line 1960, in _parse_known_args
            start_index = consume_optional(start_index)
        File "/app/tautulli/lib/argparse.py", line 1900, in consume_optional
            take_action(action, args, option_string)
        File "/app/tautulli/lib/argparse.py", line 1812, in take_action
            argument_values = self._get_values(action, argument_strings)
        File "/app/tautulli/lib/argparse.py", line 2249, in _get_values
            value = self._get_value(action, arg_string)
        File "/app/tautulli/lib/argparse.py", line 2278, in _get_value
            result = type_func(arg_string)
        File "/config/scripts/kill_stream.py", line 105, in arg_decoding
            return arg.decode(TAUTULLI_ENCODING).encode('UTF-8')
    AttributeError: 'str' object has no attribute 'decode'
```

Edit:
Most likely a python2/3 thing i guess?

**Comment by blacktwin** [comment]
You need to be using python 3.x and make sure you're using the most updated version of the script.

**Comment by blacktwin** [comment]
@lazyb0nes All good now?
