### ISSUE TITLE
AttributeError: 'str' object has no attribute 'key'

### ISSUE THREAD

**Issue by torres3490** [blacktwin/JBOPS#307]
**receiving this error after running** 
_python playlist_manager.py --action share --users "ESPANOL" --playlists "Caliente"
pause"_

Traceback (most recent call last):
  File "playlist.py", line 848, in <module>
    share_playlists(selected_playlists, users)
  File "playlist.py", line 538, in share_playlists
    plex.playlist(title).copyToUser(user)
  File "C:\Users\torre\AppData\Local\Programs\Python\Python37\lib\site-packages\plexapi\server.py", line 481, in playlist
    return self.fetchItem('/playlists', title=title)
  File "C:\Users\torre\AppData\Local\Programs\Python\Python37\lib\site-packages\plexapi\base.py", line 156, in fetchItem
    if self._checkAttrs(elem, **kwargs):
  File "C:\Users\torre\AppData\Local\Programs\Python\Python37\lib\site-packages\plexapi\base.py", line 339, in _checkAttrs
    if operator(value, query):
  File "C:\Users\torre\AppData\Local\Programs\Python\Python37\lib\site-packages\plexapi\base.py", line 13, in <lambda>
    'exact': lambda v, q: v == q,
  File "C:\Users\torre\AppData\Local\Programs\Python\Python37\lib\site-packages\plexapi\base.py", line 418, in __eq__
    return other not in [None, []] and self.key == other.key
AttributeError: 'str' object has no attribute 'key'

**Comment by blacktwin** [comment]
This might need to be defined before using the action

Change [line 538](https://github.com/blacktwin/JBOPS/blob/master/fun/playlist_manager.py#L538)
```python
plex.playlist(title).copyToUser(user)
```
to
```python
playlist = plex.playlist(title)
playlist.copyToUser(user)
```
