### ISSUE TITLE
Bug plex_api_poster_pull.py

### ISSUE THREAD

**Issue by snaj06** [blacktwin/JBOPS#325]
**Describe the bug**

Since few days, python3 plex_api_poster_pull.py crash after few second. I have 2 folder Movies and TV_Show, some cover.jpg in Movies but just few then crash with this error.
I tried on another server, same error.

```
python3 plex_api_poster_pull.py
Traceback (most recent call last):
  File "plex_api_poster_pull.py", line 73, in <module>
    urllib.request.urlretrieve(thumb_url, image_path)
  File "/usr/lib/python3.8/urllib/request.py", line 247, in urlretrieve
    with contextlib.closing(urlopen(url, data)) as fp:
  File "/usr/lib/python3.8/urllib/request.py", line 222, in urlopen
    return opener.open(url, data, timeout)
  File "/usr/lib/python3.8/urllib/request.py", line 531, in open
    response = meth(req, response)
  File "/usr/lib/python3.8/urllib/request.py", line 640, in http_response
    response = self.parent.error(
  File "/usr/lib/python3.8/urllib/request.py", line 569, in error
    return self._call_chain(*args)
  File "/usr/lib/python3.8/urllib/request.py", line 502, in _call_chain
    result = func(*args)
  File "/usr/lib/python3.8/urllib/request.py", line 649, in http_error_default
    raise HTTPError(req.full_url, code, msg, hdrs, fp)
urllib.error.HTTPError: HTTP Error 404: Not Found
```

 - OS: Linux Ubuntu
 - Python 3.8.10
 - just script plex_api_poster_pull.py

**Comment by blacktwin** [comment]
Bad token?

**Comment by snaj06** [comment]
I don't think so because I didn't change anything and it was working before. After crash (with this log) I have some covers in Movie folder so it's working few seconds (with this token) then it crashed.
