### ISSUE TITLE
Not sure but error with kill_stream.py

### ISSUE THREAD

**Issue by JFPCreations** [blacktwin/JBOPS#327]
Hi, here is an error I get when I try to setup kill_stream.py all seems to work except it does not kill the process and do not send the message. Thank you.

2022-01-21 10:01:02	ERROR	Uncaught exception: Traceback (most recent call last):
    File "/snap/tautulli/1320/plexpy/logger.py", line 341, in new_run
        old_run(*args, **kwargs)
    File "/snap/tautulli/1320/usr/lib/python3.6/threading.py", line 864, in run
        self._target(*self._args, **self._kwargs)
    File "/snap/tautulli/1320/plexpy/notifiers.py", line 3346, in run_script
        env=env)
    File "/snap/tautulli/1320/usr/lib/python3.6/subprocess.py", line 729, in __init__
        restore_signals, start_new_session)
    File "/snap/tautulli/1320/usr/lib/python3.6/subprocess.py", line 1295, in _execute_child
        restore_signals, start_new_session, preexec_fn)
UnicodeEncodeError: 'ascii' codec can't encode character '\xe9' in position 10: ordinal not in range(128)
2022-01-21 10:01:02	DEBUG	Tautulli Notifiers :: Executing script in a new thread.
2022-01-21 10:01:02	DEBUG	Tautulli Notifiers :: Full script is: ['/snap/tautulli/1320/usr/bin/python3', '/snap/tautulli/kill_stream.py', '--jbop', 'stream', '--username', (cut out name and id)

**Comment by JFPCreations** [comment]
It looks like the problem was from the snap installation. 

I reinstall it with docker image and all is working well. 

Thank you.
