### ISSUE TITLE
kill_trans_pause_notify indexerror: list index out of range. 

### ISSUE THREAD

**Issue by dejected1** [blacktwin/JBOPS#34]
Setup kill_trans_pause_notify.py to trigger scripts when paused. Script does run when stream is paused but the log shows this error: 

```
ERROR | PlexPy Notifiers :: Script error:     Traceback (most recent call last):         File "C:\JonnyWong16-plexpy-3742f33\Scripts\Weekly\kill_trans_pause_notify.py", line 61, in             video_decision = session.transcodeSessions[0].videoDecision     IndexError: list index out of range
-- | --
```

When a user on the ignore list pauses a stream, the script triggers without issue. Im using the version i found off your site: 

```
"""
Kill Plex paused video transcoding streams and receive notification.
PlexPy > Settings > Notification Agents > Scripts > Bell icon:
        [X] Notify on playback pause
PlexPy > Settings > Notification Agents > Scripts > Gear icon:
        Playback Pause: kill_trans_pause.py
"""

import sys
import requests
from plexapi.server import PlexServer


## EDIT THESE SETTINGS ##
PLEX_URL = 'http://localhost:32400'
PLEX_TOKEN = 'xxxxx'
PLEXPY_APIKEY = 'xxxxx'  # Your PlexPy API key
PLEXPY_URL = 'http://localhost:8181/'  # Your PlexPy URL

KILL_MESSAGE = 'This stream has ended due to being paused and transcoding.'

USER_IGNORE = ('') # ('Username','User2')

SUBJECT_TEXT = "Killed Paused Transcoded Stream."
BODY_TEXT = "Killed {user}'s paused transcoded stream of {title}."

AGENT_ID = 14  # Notification agent ID for PlexPy
# Find Notification agent ID here:
# https://github.com/JonnyWong16/plexpy/blob/master/API.md#notify

##/EDIT THESE SETTINGS ##

sess = requests.Session()
sess.verify = False
plex = PlexServer(PLEX_URL, PLEX_TOKEN, session=sess)

def send_notification(subject_text, body_text):
    # Send the notification through PlexPy
    payload = {'apikey': PLEXPY_APIKEY,
               'cmd': 'notify',
               'agent_id': AGENT_ID,
               'subject': subject_text,
               'body': body_text}

    try:
        r = requests.post(PLEXPY_URL.rstrip('/') + '/api/v2', params=payload)
        response = r.json()

        if response['response']['result'] == 'success':
            sys.stdout.write("Successfully sent PlexPy notification.")
        else:
            raise Exception(response['response']['message'])
    except Exception as e:
        sys.stderr.write("PlexPy API 'notify' request failed: {0}.".format(e))
        return None


for session in plex.sessions():
    username = session.usernames[0]
    state = session.players[0].state
    video_decision = session.transcodeSessions[0].videoDecision
    title = (session.grandparentTitle + ' - ' if session.type == 'episode' else '') + session.title

    if video_decision == 'transcode' and state == 'paused' and username not in USER_IGNORE:
        sys.stdout.write("Killing {user}'s stream of {title}.".format(user=username, title=title))
        session.stop(reason=KILL_MESSAGE)
        send_notification(SUBJECT_TEXT, BODY_TEXT.format(user=username, title=title))
```

**Comment by dejected1** [comment]
ok so l left it enabled not thinking anything of it. I am now getting notified over and over for the same stream. The stream is 24 hours old and has been stopped by the script 5 times and counting. 


2017-12-18 13:03:24 | DEBUG | PlexPy ActivityHandler :: Session 188 has stopped.
-- | -- | --
2017-12-18 13:03:23 | DEBUG | PlexPy ActivityHandler :: Session 188 has been resumed.
2017-12-18 13:03:11 | INFO | PlexPy Notifiers :: Script notification sent.
2017-12-18 13:03:11 | DEBUG | PlexPy Notifiers :: Script returned:     Killing gbatt's stream of Lilo & Stitch.Successfully sent PlexPy notification.
2017-12-18 13:03:11 | INFO | PlexPy Notifiers :: PushBullet notification sent.
2017-12-18 13:03:11 | DEBUG | Sending Pushbullet notification.
2017-12-18 13:03:11 | DEBUG | PlexPy APIv2 :: Cleaned kwargs: {'body': u"Killed gbatt's paused transcoded stream of Lilo & Stitch.", 'agent_id': u'6', 'subject': u'Killed Paused Transcoded Stream.'}
2017-12-18 13:03:11 | DEBUG | PlexPy APIv2 :: API called with kwargs: {'body': u"Killed gbatt's paused transcoded stream of Lilo & Stitch.", 'apikey': u'********d0', 'cmd': u'notify', 'agent_id': u'6', 'subject': u'Killed Paused Transcoded Stream.'}
2017-12-18 13:03:09 | DEBUG | PlexPy Notifiers :: Executing script in a new thread.
2017-12-18 13:03:09 | DEBUG | PlexPy Notifiers :: Full script is: ['python', 'C:\\JonnyWong16-plexpy-3742f33\\Scripts\\Weekly\\kill_trans_pause_notify.py', '-sn', '', '-ena', 'Lilo & Stitch', '-ssn', '00', '-enu', '00', '-srv', 'dejected-hadron', '-med', 'movie', '-pos', 'https://i.imgur.com/b00Ma4B.jpg', '-tt', 'Lilo & Stitch', '-sum', 'A lonely Hawaiian girl named Lilo is being raised by her older sister, Nani, after their parents die -- under the watch of social worker Cobra Bubbles. When Lilo adopts a funny-looking dog and names him "Stitch," she doesn\'t realize her new best friend is a wacky alien created by mad scientist Dr. Jumba.', '-lbn', 'Brat Movies', '-grk', '']
2017-12-18 13:03:09 | DEBUG | PlexPy Notifiers :: Trying to run notify script, action: pause, arguments: [u'-sn', u'', u'-ena', u'Lilo & Stitch', u'-ssn', u'00', u'-enu', u'00', u'-srv', u'dejected-hadron', u'-med', u'movie', u'-pos', u'https://i.imgur.com/b00Ma4B.jpg', u'-tt', u'Lilo & Stitch', u'-sum', u'A lonely Hawaiian girl named Lilo is being raised by her older sister, Nani, after their parents die -- under the watch of social worker Cobra Bubbles. When Lilo adopts a funny-looking dog and names him "Stitch," she doesn\'t realize her new best friend is a wacky alien created by mad scientist Dr. Jumba.', u'-lbn', u'Brat Movies', u'-grk', u'']
2017-12-18 13:03:09 | DEBUG | PlexPy ActivityHandler :: Session 188 has been paused.
2017-12-18 13:03:02 | DEBUG | PlexPy ActivityHandler :: Session 188 has started with ratingKey 42669.

and on and on it goes.

**Comment by blacktwin** [comment]
Thanks for all the detail but please use the [Markdown Code and Syntax Highlighting](https://github.com/adam-p/markdown-here/wiki/Markdown-Cheatsheet#code-and-syntax-highlighting). I edited your post to clean it up.

First error, can you provide more of the log? If music is paused for example you would see this. I'll have to do something about that.

> When a user on the ignore list pauses a stream, the script triggers without **issue.**

So the user is ignored, correct?

> and on and on it goes.

Well yeah. I assume that the user is pausing and transcoding stream over and over? Or am I missing something?

**Comment by carnivorouz** [comment]
Same issue for me.  No matter if user is in ignore list or not the result is the same:
```
2018-04-04 23:40:14 | ERROR | Tautulli Notifiers :: Script error:     Traceback (most recent call last):         File "/mnt/Media/Scripts/kill_trans_pause.py", line 48, in <module>             session_key = int(sys.argv[1])     IndexError: list index out of range
```

**Comment by blacktwin** [comment]
@carnivorouz can you provide more of the logs?
