### ISSUE TITLE
help please with kill streams

### ISSUE THREAD

**Issue by daveftw84** [blacktwin/JBOPS#349]
Traceback (most recent call last):
    File "/scripts/kill_streams.py", line 589, in <module>
      opts = parser.parse_args()
    File "/usr/lib/python3.9/argparse.py", line 1820, in parse_args
      args, argv = self.parse_known_args(args, namespace)
    File "/usr/lib/python3.9/argparse.py", line 1853, in parse_known_args
      namespace, args = self._parse_known_args(args, namespace)
    File "/usr/lib/python3.9/argparse.py", line 2062, in _parse_known_args
      start_index = consume_optional(start_index)
    File "/usr/lib/python3.9/argparse.py", line 2002, in consume_optional
      take_action(action, args, option_string)
    File "/usr/lib/python3.9/argparse.py", line 1914, in take_action
      argument_values = self._get_values(action, argument_strings)
    File "/usr/lib/python3.9/argparse.py", line 2445, in _get_values
      value = self._get_value(action, arg_string)
    File "/usr/lib/python3.9/argparse.py", line 2478, in _get_value
      result = type_func(arg_string)
    File "/scripts/kill_streams.py", line 105, in arg_decoding
      return arg.decode(TAUTULLI_ENCODING).encode('UTF-8')
  AttributeError: 'str' object has no attribute 'decode'

**Comment by blacktwin** [comment]
Update the script.
