### ISSUE TITLE
rating_key argument

### ISSUE THREAD

**Issue by Ritooon** [blacktwin/JBOPS#380]
Hi there,

Can someone help me with the mandatory argument "rating_key" please. I don't really know what if refers to.
I tried "0" as a value, got this error : 

```
Tautulli Notifiers :: Script error:
    Traceback (most recent call last):
        File "/config/scripts/hide_episode_spoilers.py", line 119, in <module>
            modify_episode_artwork(plex, **vars(opts))
        File "/config/scripts/hide_episode_spoilers.py", line 44, in modify_episode_artwork
            item = plex.fetchItem(rating_key)
        File "/app/tautulli/lib/plexapi/base.py", line 173, in fetchItem
            data = self._server.query(ekey)
        File "/app/tautulli/lib/plexapi/server.py", line 753, in query
            raise NotFound(message)
    plexapi.exceptions.NotFound: (404) not_found; http://[MYPLEXIP]:[MYPLEXPORT]/library/metadata/0 <html><head><title>Not Found</title></head><body><h1>404 Not Found</h1></body></html>
```

I replaced my real IP and port by [MYPLEXIP] and [MYPLEXPORT] form the log.

**Comment by Ritooon** [comment]
My issue was I don't know how to read ahah : "Note: Test with the real values since parameters will not be substituted. (i.e. Use "Game of Thrones" not {title})" my bad.
Got another error now, will investigate
