### ISSUE TITLE
IndexError: list index out of range in kill_trans_library.py

### ISSUE THREAD

**Issue by mescon** [blacktwin/JBOPS#41]
I only have ``TARGET_LIBRARIES = ['25'] # Library IDs`` set.
In Tautulli I have set this argument passed on playback start: ``{section_id}`` and nothing else.
plexapi and requests is installed.

When I try transcoding something in this library, the script executes and Tautulli gives this output:
```
2018-01-22 17:18:07 - DEBUG   :: Thread-1 : Tautulli Notifiers :: Trying to run notify script, action: play, arguments: [u'25']
2018-01-22 17:18:07 - DEBUG   :: Thread-1 : Tautulli Notifiers :: Full script is: ['python', u'/opt/JBOPS/killstream/kill_trans_library.py', u'25']
2018-01-22 17:18:07 - DEBUG   :: Thread-1 : Tautulli Notifiers :: Executing script in a new thread.
2018-01-22 17:18:08 - ERROR   :: Thread-30 : Tautulli Notifiers :: Script error:
  /usr/lib/python2.7/dist-packages/urllib3/connectionpool.py:854: InsecureRequestWarning: Unverified HTTPS request is being made. Adding certificate verification is strongly advised. See: https://urllib3.readthedocs.io/en/latest/advanced-usage.html#ssl-warnings
    InsecureRequestWarning)
  /usr/lib/python2.7/dist-packages/urllib3/connectionpool.py:854: InsecureRequestWarning: Unverified HTTPS request is being made. Adding certificate verification is strongly advised. See: https://urllib3.readthedocs.io/en/latest/advanced-usage.html#ssl-warnings
    InsecureRequestWarning)
  /usr/lib/python2.7/dist-packages/urllib3/connectionpool.py:854: InsecureRequestWarning: Unverified HTTPS request is being made. Adding certificate verification is strongly advised. See: https://urllib3.readthedocs.io/en/latest/advanced-usage.html#ssl-warnings
    InsecureRequestWarning)
  Traceback (most recent call last):
    File "/opt/JBOPS/killstream/kill_trans_library.py", line 52, in &lt;module&gt;
      trans_dec = session.transcodeSessions[0].videoDecision
  IndexError: list index out of range
```
I tried setting both ``http`` and ``https``.
When I do http, this is the output is:
```
2018-01-22 17:31:26 - DEBUG   :: Thread-2 : Tautulli Notifiers :: Trying to run notify script, action: play, arguments: [u'25']
2018-01-22 17:31:26 - DEBUG   :: Thread-2 : Tautulli Notifiers :: Full script is: ['python', u'/opt/JBOPS/killstream/kill_trans_library.py', u'25']
2018-01-22 17:31:26 - DEBUG   :: Thread-2 : Tautulli Notifiers :: Executing script in a new thread.
2018-01-22 17:31:26 - ERROR   :: Thread-35 : Tautulli Notifiers :: Script error:
  Traceback (most recent call last):
    File "/opt/JBOPS/killstream/kill_trans_library.py", line 40, in &lt;module&gt;
      plex = PlexServer(PLEX_URL, PLEX_TOKEN, session=sess)
    File "/usr/local/lib/python2.7/dist-packages/plexapi/server.py", line 101, in __init__
      data = self.query(self.key, timeout=timeout)
    File "/usr/local/lib/python2.7/dist-packages/plexapi/server.py", line 340, in query
      response = method(url, headers=headers, timeout=timeout, **kwargs)
    File "/usr/lib/python2.7/dist-packages/requests/sessions.py", line 515, in get
      return self.request('GET', url, **kwargs)
    File "/usr/lib/python2.7/dist-packages/requests/sessions.py", line 502, in request
      resp = self.send(prep, **send_kwargs)
    File "/usr/lib/python2.7/dist-packages/requests/sessions.py", line 612, in send
      r = adapter.send(request, **kwargs)
    File "/usr/lib/python2.7/dist-packages/requests/adapters.py", line 490, in send
      raise ConnectionError(err, request=request)
  requests.exceptions.ConnectionError: ('Connection aborted.', error(104, 'Connection reset by peer'))
```
I made sure the Plex server allowed unencrypted connections when trying with http.

What am I doing wrong?
Thanks for a bunch of great scripts - looks like exactly what I need, if I could just get it working! :-)

**Comment by blacktwin** [comment]
I've updated the script. Please try. 

I first error may have been due to another active session that was being checked and it was not transcoding. If there is a session that isn't transcoding then the `transcodeSessions` is empty and calling `transcodeSessions[0].videoDecision` will error. 

As for the second error, I'm not sure. What do you have for your PLEX_URL?

**Comment by mescon** [comment]
Yay, seems to be working now!

My Plex URL is:

``PLEX_URL = 'https://10.9.0.3:32400'``
Which is my server...

**Comment by mescon** [comment]
I was a bit quick to say it all works now. It seems that ALL transcodes are killed, and not just the ones in my Movies/Remux library.

The Remux library has ID 25.

``TARGET_LIBRARIES = ['25'] # Library IDs``

It seems to match EVERYTHING even though I specifically only have ID 25 targeted. Any clue?

**Comment by blacktwin** [comment]
Yeah. I forgot the most important part, the actual check against the TARGETED_LIBRARIES..... It's updated.

**Comment by mescon** [comment]
Thanks man!
