### ISSUE TITLE
Inactive User script fails when trying to remove a user

### ISSUE THREAD

**Issue by Lonewolf147** [blacktwin/JBOPS#424]
When the script runs, it returns the following error when it tries to remove a user:

`Traceback (most recent call last):
File "/config/scripts/purge_inactive_users.py", line 154, in
ACCOUNT.removeFriend(PLEX_USERS[UID])
File "/lsiopy/lib/python3.11/site-packages/plexapi/myplex.py", line 455, in removeFriend
return self.query(url, self._session.delete)
^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
File "/lsiopy/lib/python3.11/site-packages/plexapi/myplex.py", line 245, in query
raise BadRequest(message)
plexapi.exceptions.BadRequest: (410) gone; https://plex.tv/api/friends/68671525`

**Link to script with bug/issue**
[https://github.com/blacktwin/JBOPS/blob/master/utility/remove_inactive_users.py](url)

**To Reproduce**

1. Go to 'User Scripts' under unraid settings
2. Click on 'Run Script' for the specified script
3. See error

**Expected behavior**
Users that meet the inactive threshold in the script should be removed.

**Additional context**
This script had been working fine, then this started happening a few weeks ago.

**Comment by blacktwin** [comment]
I think this might be related to https://github.com/blacktwin/JBOPS/issues/435#issuecomment-2673347106
