### ISSUE TITLE
Remove Inactive Users API Issue

### ISSUE THREAD

**Issue by yaitsbilly** [blacktwin/JBOPS#427]
**Describe the bug**

Script stopped working and started giving this error message.

I noticed Tatulli uses the first API link, this link has a lot more users on there that I am NOT sharing with.
https://plex.tv/api/users?X-Plex-Token=XXX

And this link shows the exact users who I'm sharing with.
https://plex.tv/api/servers/XXX/shared_servers?X-Plex-Token=XXX

**Provide logs**

freepo6 was last seen 14 days, 6 hours, 40 minutes, 56 seconds ago, and has reached their shareless threshold. Removing.
Traceback (most recent call last):

  File "C:\Users\Administrator\Documents\Plex Remove Inactive Users\remove.bat", line 104, in <module>
    ACCOUNT.removeFriend(PLEX_USERS[UID])
  File "C:\Users\Administrator\AppData\Local\Programs\Python\Python311\Lib\site-packages\plexapi\myplex.py", line 465, in removeFriend
    return self.query(url, self._session.delete)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Administrator\AppData\Local\Programs\Python\Python311\Lib\site-packages\plexapi\myplex.py", line 246, in query
    raise BadRequest(message)
plexapi.exceptions.BadRequest: (410) gone; https://plex.tv/api/friends/229720260 <?xml version="1.0" encoding="UTF-8"?> <Response code="410" status="This endpoint was deprecated and removed"/>

**Link to script with bug/issue**

**To Reproduce**

Run script as is.

**Expected behavior**
Remove users

**Desktop (please complete the following information):**
 - OS: windows server 2022
 - Python version 3.11.4
 - PlexAPI version 4.15.7

**Comment by blacktwin** [comment]
I think this might be related to https://github.com/blacktwin/JBOPS/issues/435#issuecomment-2673347106
