### ISSUE TITLE
Error:  "TypeError: 'NoneType' object has no attribute '__getitem__"

### ISSUE THREAD

**Issue by seanvree** [blacktwin/JBOPS#5]
OS:  Windows10E 1703 X64
Plexpy:  1.4
Python Version: | 2.7.13 (v2.7.13:a06454b1afa1, Dec 17 2016, 20:42:59) [MSC v.1500 32 bit (Intel)]

ISSUE:
Scripts used:  kill_trans_pause.py

So, the script runs and does appear to kill the stream, but I am getting the below python error:

```

     PlexPy Notifiers :: Script error: 
    Traceback (most recent call last): 
        File "C:\JBOPS\killstream\kill_trans_pause.py", line 67, in 
            for s in response['MediaContainer']['Video']: 
    TypeError: 'NoneType' object has no attribute '__getitem__'
```

so my full log after it killed looked like this:

```
 2017-07-26 09:18:14    DEBUG    PlexPy ActivityHandler :: Removing sessionKey 110 ratingKey 170214 from session queue
2017-07-26 09:18:14    DEBUG    PlexPy ActivityProcessor :: Fetching metadata for item ratingKey 170214
2017-07-26 09:18:14    DEBUG    PlexPy ActivityHandler :: Session 110 has stopped.
2017-07-26 09:17:55    ERROR    PlexPy Notifiers :: Script error: 
    Traceback (most recent call last): 
        File "C:\JBOPS\killstream\kill_trans_pause.py", line 67, in 
            for s in response['MediaContainer']['Video']: 
    TypeError: 'NoneType' object has no attribute '__getitem__'
2017-07-26 09:17:54    DEBUG    PlexPy Notifiers :: Executing script in a new thread.
```

**Comment by blacktwin** [comment]
@seanvree what other streams are playing while the script runs? It's likely that a none video stream (track, photo) is playing. I can correct this with an If statement.

**Comment by seanvree** [comment]
When I've tested, the stream mentioned above is the only stream (transcode or not).  But I have NOT tested when other streams are on-going.

**Comment by blacktwin** [comment]
@seanvree I've updated the script. Can you please try again.

**Comment by seanvree** [comment]
@blacktwin will do, hang tight

**Comment by seanvree** [comment]
Fixed!


```

2017-07-31 05:34:05 | DEBUG | PlexPy ActivityHandler :: Removing sessionKey 240 ratingKey 172106 from session queue
-- | -- | --
2017-07-31 05:34:05 | DEBUG | PlexPy ActivityProcessor :: Fetching metadata for item ratingKey 172106
2017-07-31 05:34:05 | DEBUG | PlexPy ActivityHandler :: Session 240 has stopped.
2017-07-31 05:33:56 | INFO | PlexPy Notifiers :: Script notification sent.
2017-07-31 05:33:55 | DEBUG | PlexPy Notifiers :: Executing script in a new thread.
2017-07-31 05:33:55 | DEBUG | PlexPy Notifiers :: Full script is: ['python', 'C:\\JBOPS\\killstream\\kill_trans_pause.py', '240']
2017-07-31 05:33:55 | DEBUG | PlexPy Notifiers :: Trying to run notify script, action: pause, arguments: [u'240']
2017-07-31 05:33:54 | DEBUG | PlexPy ActivityHandler :: Session 240 has been paused.

```
