### ISSUE TITLE
Aired Today Playlist Not Created

### ISSUE THREAD

**Issue by WallaWallaWA** [blacktwin/JBOPS#54]
Playlists for current day no longer being created, with the following error message:
```
Traceback (most recent call last):
  File "C:\Python27\Scripts\new_create_current_day_playlist.py", line 70, in <module>
    play_lst = find_air_dates(get_all_content(LIBRARY_NAMES))
  File "C:\Python27\Scripts\new_create_current_day_playlist.py", line 38, in get_all_content
    for child in plex.library.section(library).all():
  File "C:\python36\lib\site-packages\plexapi\library.py", line 383, in all
    return self.fetchItems(key, **kwargs)
  File "C:\python36\lib\site-packages\plexapi\base.py", line 147, in fetchItems
    return self.findItems(data, cls, ekey, **kwargs)
  File "C:\python36\lib\site-packages\plexapi\base.py", line 163, in findItems
    item = self._buildItemOrNone(elem, cls, initpath)
  File "C:\python36\lib\site-packages\plexapi\base.py", line 86, in _buildItemOrNone
    return self._buildItem(elem, cls, initpath)
  File "C:\python36\lib\site-packages\plexapi\base.py", line 78, in _buildItem
    return ecls(self._server, elem, initpath)
  File "C:\python36\lib\site-packages\plexapi\base.py", line 47, in __init__
    self._loadData(data)
  File "C:\python36\lib\site-packages\plexapi\video.py", line 108, in _loadData
    Video._loadData(self, data)
  File "C:\python36\lib\site-packages\plexapi\video.py", line 32, in _loadData
    self.addedAt = utils.toDatetime(data.attrib.get('addedAt'))
  File "C:\python36\lib\site-packages\plexapi\utils.py", line 176, in toDatetime
    value = datetime.fromtimestamp(int(value))
OSError: [Errno 22] Invalid argument
PS C:\Python27>
```

**Comment by blacktwin** [comment]
try updating plexapi `pip install plexapi --upgrade`. Check your `LIBRARY_NAMES` list.

**Comment by WallaWallaWA** [comment]
Thanks. Did the update and ran a new script based on a direct copy of the script here on github. Libraries did not change ('Movies' and 'TV Shows') and received the following, which appears to be the same error as before:
```
Traceback (most recent call last):
  File "C:\Python27\Scripts\new_create_current_day_playlist.py", line 70, in <module>
    play_lst = find_air_dates(get_all_content(LIBRARY_NAMES))
  File "C:\Python27\Scripts\new_create_current_day_playlist.py", line 38, in get_all_content
    for child in plex.library.section(library).all():
  File "C:\python36\lib\site-packages\plexapi\library.py", line 383, in all
    return self.fetchItems(key, **kwargs)
  File "C:\python36\lib\site-packages\plexapi\base.py", line 147, in fetchItems
    return self.findItems(data, cls, ekey, **kwargs)
  File "C:\python36\lib\site-packages\plexapi\base.py", line 163, in findItems
    item = self._buildItemOrNone(elem, cls, initpath)
  File "C:\python36\lib\site-packages\plexapi\base.py", line 86, in _buildItemOrNone
    return self._buildItem(elem, cls, initpath)
  File "C:\python36\lib\site-packages\plexapi\base.py", line 78, in _buildItem
    return ecls(self._server, elem, initpath)
  File "C:\python36\lib\site-packages\plexapi\base.py", line 47, in __init__
    self._loadData(data)
  File "C:\python36\lib\site-packages\plexapi\video.py", line 120, in _loadData
    Video._loadData(self, data)
  File "C:\python36\lib\site-packages\plexapi\video.py", line 32, in _loadData
    self.addedAt = utils.toDatetime(data.attrib.get('addedAt'))
  File "C:\python36\lib\site-packages\plexapi\utils.py", line 176, in toDatetime
    value = datetime.fromtimestamp(int(value))
OSError: [Errno 22] Invalid argument
```
Verified plex token, path, etc. Not aware of anything that has changed.  Thanks for the quick response.
[new_create_current_day_playlist.txt](https://github.com/blacktwin/JBOPS/files/1822899/new_create_current_day_playlist.txt)

**Comment by WallaWallaWA** [comment]
Ok, fixed the conflict between python 2 and 3, but now get an error on:
```
PS C:\Python27> python.exe C:\Python27\Scripts\new_create_current_day_playlist.py
Traceback (most recent call last):
  File "C:\Python27\Scripts\new_create_current_day_playlist.py", line 77, in <module>
    play_lst = find_air_dates(get_all_content(LIBRARY_NAMES))
  File "C:\Python27\Scripts\new_create_current_day_playlist.py", line 45, in get_all_content
    for child in plex.library.section(library).all():
  File "C:\Python27\lib\site-packages\plexapi\library.py", line 132, in all
    return utils.listItems(self.server, '/library/sections/%s/all' % self.key)
  File "C:\Python27\lib\site-packages\plexapi\utils.py", line 237, in listItems
    items.append(buildItem(server, elem, path, bytag))
  File "C:\Python27\lib\site-packages\plexapi\utils.py", line 131, in buildItem
    return cls(server, elem, initpath)
  File "C:\Python27\lib\site-packages\plexapi\video.py", line 14, in __init__
    super(Video, self).__init__(data, initpath, server)
  File "C:\Python27\lib\site-packages\plexapi\utils.py", line 44, in __init__
    self._loadData(data)
  File "C:\Python27\lib\site-packages\plexapi\video.py", line 64, in _loadData
    Video._loadData(self, data)
  File "C:\Python27\lib\site-packages\plexapi\video.py", line 18, in _loadData
    self.addedAt = utils.toDatetime(data.attrib.get('addedAt', NA))
  File "C:\Python27\lib\site-packages\plexapi\utils.py", line 282, in toDatetime
    else: value = datetime.fromtimestamp(int(value))
ValueError: timestamp out of range for platform localtime()/gmtime() function
PS C:\Python27>
```
Tried substituting `#today = time.localtime(time.time())` for `datetime.datetime.now().date()` but get an error that `NameError: name 'time' is not defined`. Sorry for all this; really liked having the today's playlist, but can live without it if this can't be fixed.

**Comment by blacktwin** [comment]
try this, edit the `get_all_content()` function:

```python
def get_all_content(library_name):
    # Get all movies or episodes from LIBRARY_NAME
    child_lst = []
    for library in library_name:
        try:                                   # <--- adding this
            for child in plex.library.section(library).all():
                if child.type == 'movie':
                    child_lst += [child]
                elif child.type == 'show':
                    child_lst += child.episodes()
                else:
                    pass
        except Exception as e:           # <--- adding this
            print(e)                           # <--- adding this
            pass                                # <--- adding this
    return child_lst
```

it could be that you have a file that has it's `addedAt` data as too far in the future from your local machine time, maybe

**Comment by WallaWallaWA** [comment]
Thanks. Now getting the following:
```
PS C:\python27> python.exe C:\Python27\Scripts\modified_new_create_current_day_playlist.py
timestamp out of range for platform localtime()/gmtime() function
timestamp out of range for platform localtime()/gmtime() function
Traceback (most recent call last):
  File "C:\Python27\Scripts\modified_new_create_current_day_playlist.py", line 76, in <module>
    plex.createPlaylist(TODAY_PLAY_TITLE, play_lst)
  File "C:\Python27\lib\site-packages\plexapi\server.py", line 77, in createPlaylist
    return Playlist.create(self, title, items)
  File "C:\Python27\lib\site-packages\plexapi\playlist.py", line 82, in create
    uuid = items[0].section().uuid
IndexError: list index out of range
PS C:\python27>
```
Checked, and I have some specials and outtakes that do not have release dates, nor are there dates listed for them in the TVDB; however, those episodes existed previously when the script used to work, so not certain that that is the cause.

**Comment by blacktwin** [comment]
edit to add the following:
```python
remove_old()
play_lst = find_air_dates(get_all_content(LIBRARY_NAMES))
print(play_lst)            # <----- Add this
# Create Playlist
plex.createPlaylist(TODAY_PLAY_TITLE, play_lst)
```
This will print the play_lst items to see what's causing the error.

**Comment by WallaWallaWA** [comment]
Thanks. Returned same error message, nothing printed.
```
PS C:\Python27> python.exe C:\Python27\Scripts\modified_new_create_current_day_playlist.py
timestamp out of range for platform localtime()/gmtime() function
timestamp out of range for platform localtime()/gmtime() function
[ ]
Traceback (most recent call last):
  File "C:\Python27\Scripts\modified_new_create_current_day_playlist.py", line 77, in <module>
    plex.createPlaylist(TODAY_PLAY_TITLE, play_lst)
  File "C:\Python27\lib\site-packages\plexapi\server.py", line 77, in createPlaylist
    return Playlist.create(self, title, items)
  File "C:\Python27\lib\site-packages\plexapi\playlist.py", line 82, in create
    uuid = items[0].section().uuid
IndexError: list index out of range
PS C:\Python27>
```
py file attached as modified.

[modified_new_create_current_day_playlist.txt](https://github.com/blacktwin/JBOPS/files/1824957/modified_new_create_current_day_playlist.txt)

**Comment by blacktwin** [comment]
ok so nothing is making into the list. So you have nothing that was aired today in history. 

```python
today = datetime.datetime.now().date()
print(today)  # <--- add this
```

```python
def find_air_dates(content_lst):
    # Find what aired with today's month-day
    aired_lst = []
    for video in content_lst:
        try:
            ad_month = str(video.originallyAvailableAt.month)
            ad_day = str(video.originallyAvailableAt.day)
            if ad_month == str(today.month) and ad_day == str(today.day):
                aired_lst += [[video] + [str(video.originallyAvailableAt)]]
        except Exception as e:
            print(video)       #   <----- add this
            print(e)              #  <------uncomment
            pass
```

**Comment by WallaWallaWA** [comment]
Thanks. It did return today's date, but nothing else. Same error message, so if nothing aired on 3/19/2018 understand there would not be a playlist created if we're limiting to today, but a quick look reveals that there were 5 TV episodes that aired on 3/19/2017 so would expect that a playlist would be created for all aired movie/tv for 3/19, correct?
```
PS C:\Python27> python.exe C:\Python27\Scripts\modified_new_create_current_day_playlist.py
2018-03-19
timestamp out of range for platform localtime()/gmtime() function
timestamp out of range for platform localtime()/gmtime() function
[]
Traceback (most recent call last):
  File "C:\Python27\Scripts\modified_new_create_current_day_playlist.py", line 79, in <module>
    plex.createPlaylist(TODAY_PLAY_TITLE, play_lst)
  File "C:\Python27\lib\site-packages\plexapi\server.py", line 77, in createPlaylist
    return Playlist.create(self, title, items)
  File "C:\Python27\lib\site-packages\plexapi\playlist.py", line 82, in create
    uuid = items[0].section().uuid
IndexError: list index out of range
PS C:\Python27>
```

**Comment by blacktwin** [comment]
I've updated the script to do nothing if the list is empty. But I think your libraries are messed up somehow. 

```python
def get_all_content(library_name):
    # Get all movies or episodes from LIBRARY_NAME
    child_lst = []
    for library in library_name:
        try:
            for child in plex.library.section(library).all():
                print('test', child)     # <---- add this
                if child.type == 'movie':
                    child_lst += [child]
                elif child.type == 'show':
                    child_lst += child.episodes()
                else:
                    pass
        except Exception as e:
            print(e)
    return child_lst
```

**Comment by WallaWallaWA** [comment]
Thanks. Just tried the new change and it returns the same as before.
```
PS C:\Python27> python.exe C:\Python27\Scripts\modified_new_create_current_day_playlist.py
>>
2018-03-19
timestamp out of range for platform localtime()/gmtime() function
timestamp out of range for platform localtime()/gmtime() function
[]
Traceback (most recent call last):
  File "C:\Python27\Scripts\modified_new_create_current_day_playlist.py", line 79, in <module>
    plex.createPlaylist(TODAY_PLAY_TITLE, play_lst)
  File "C:\Python27\lib\site-packages\plexapi\server.py", line 77, in createPlaylist
    return Playlist.create(self, title, items)
  File "C:\Python27\lib\site-packages\plexapi\playlist.py", line 82, in create
    uuid = items[0].section().uuid
IndexError: list index out of range
PS C:\Python27>
```
Agree that if I'm the only one with this issue the fault lies with my system. I'm reviewing all movies/tv shows to ensure that each has a good air/release date and will see if that helps.  Appreciate all the time and effort on this and sorry to have taken up so much time for just one person's issue. This is a great script, and I will reply if I can get the libraries vetted and if the script runs - thanks once more for all the help!
