### ISSUE TITLE
PlexPY error:  "kill_stream     ImportError: No module named create_wait_kill_trans"

### ISSUE THREAD

**Issue by seanvree** [blacktwin/JBOPS#6]
OS: Windows10E 1703 X64
Plexpy: 1.4
Python Version: | 2.7.13 (v2.7.13:a06454b1afa1, Dec 17 2016, 20:42:59) [MSC v.1500 32 bit (Intel)]

ISSUE:

create_wait_kill_trans.py Script does not kill stream when client transcode is paused. 

Possibly related to https://github.com/blacktwin/JBOPS/issues/5

Config:

```
## EDIT THESE SETTINGS ##

PLEX_HOST = 'localhost'
PLEX_PORT = 32400
PLEX_SSL = ''  # s or ''
PLEX_TOKEN = 'DTQyxxxxxxxxkxgnGbvSj7'

TIMEOUT = 120
INTERVAL = 10
```

PlexPY Logs:

```

2017-07-26 22:02:00 | DEBUG | PlexPy Monitor :: Library item 171122 has been added to Plex.
-- | -- | --
2017-07-26 22:01:47 | ERROR | PlexPy Notifiers :: Script error:     Traceback (most recent call last):         File "ce4v0py551wome68wdujlktq.py", line 3, in             from create_wait_kill_trans import kill_stream     ImportError: No module named create_wait_kill_trans
2017-07-26 22:01:46 | DEBUG | PlexPy Notifiers :: Executing script in a new thread.
2017-07-26 22:01:46 | DEBUG | PlexPy Notifiers :: Full script is: ['python', 'C:\\JBOPS\\killstream\\create_wait_kill_trans.py', '8']
2017-07-26 22:01:46 | DEBUG | PlexPy Notifiers :: Trying to run notify script, action: pause, arguments: [u'8']
2017-07-26 22:01:45 | DEBUG | PlexPy ActivityHandler :: Session 8 has been paused.

```

**Comment by blacktwin** [comment]
@seanvree Do you have a Plex Pass?

**Comment by seanvree** [comment]
@blacktwin  I do.

**Comment by seanvree** [comment]
@blacktwin  - you have any idea about this?

**Comment by blacktwin** [comment]
OS? Check permissions? The subscript can't find the kill script. They should be in the same directory.

**Comment by seanvree** [comment]
How would the subscript not be able to find the kill script if the kill script is the original script that was called from PlexPY?

**Comment by blacktwin** [comment]
@seanvree OK that helps. The subscript is being created in the wrong directory. It should be created in the killstream directory. I'll fix it soon.

**Comment by blacktwin** [comment]
@seanvree Updated. Can you try again?

**Comment by seanvree** [comment]
Yup. hang tight!

**Comment by seanvree** [comment]
@blacktwin  okay, so it looks like it worked, but still getting an error in the PlexPY logs:

```

2017-07-31 06:50:58 | DEBUG | PlexPy Monitor :: Removing sessionKey 2 ratingKey 172106 from session queue
-- | -- | --
2017-07-31 06:50:58 | DEBUG | PlexPy ActivityProcessor :: Fetching metadata for item ratingKey 172106
2017-07-31 06:50:58 | DEBUG | PlexPy Monitor :: Session 2 has stopped.
2017-07-31 06:50:51 | DEBUG | PlexPy APIv2 :: Cleaned kwargs: {}
2017-07-31 06:50:51 | DEBUG | PlexPy APIv2 :: API called with kwargs: {'cmd': u'get_activity', 'apikey': u'********39'}
2017-07-31 06:50:00 | ERROR | PlexPy Notifiers :: Script error:     Traceback (most recent call last):         File "e9df8eefc3f6ecd-com-plexapp-android.py", line 3, in             from create_wait_kill_trans import kill_stream     ImportError: No module named create_wait_kill_trans
2017-07-31 06:49:59 | DEBUG | PlexPy Notifiers :: Executing script in a new thread.
2017-07-31 06:49:59 | DEBUG | PlexPy Notifiers :: Full script is: ['python', 'C:\\JBOPS\\killstream\\create_wait_kill_trans.py', '2']
2017-07-31 06:49:59 | DEBUG | PlexPy Notifiers :: Trying to run notify script, action: pause, arguments: [u'2']
2017-07-31 06:49:58 | DEBUG | PlexPy Monitor :: Session 2 has been paused.


```

**Comment by blacktwin** [comment]
@seanvree updated again. Please try.

**Comment by seanvree** [comment]
@blacktwin  Killed stream, different error this time:

```

2017-07-31 08:37:15 | DEBUG | PlexPy APIv2 :: API called with kwargs: {'cmd': u'get_activity', 'apikey': u'********39'}
-- | -- | --
2017-07-31 08:37:04 | DEBUG | PlexPy APIv2 :: Cleaned kwargs: {}
2017-07-31 08:37:04 | DEBUG | PlexPy APIv2 :: API called with kwargs: {'cmd': u'get_activity', 'apikey': u'********39'}
2017-07-31 08:36:58 | ERROR | PlexPy Notifiers :: Script error:     Traceback (most recent call last):         File "C:\JBOPS\killstream\e9df8eefc3f6ecd-com-plexapp-android.py", line 11, in             x += kill_stream(sessionID, message, 10, n, 'seanvree@hotmail.com', 'David Brent: Life on the Road', '1')         File "C:\JBOPS\killstream\create_wait_kill_trans.py", line 83, in kill_stream             if response['MediaContainer']['Video']:     KeyError: 'Video'
2017-07-31 08:36:55 | DEBUG | PlexPy ActivityHandler :: Removing sessionKey 1 ratingKey 172106 from session queue
2017-07-31 08:36:55 | DEBUG | PlexPy ActivityProcessor :: Fetching metadata for item ratingKey 172106
2017-07-31 08:36:54 | DEBUG | PlexPy ActivityHandler :: Session 1 has stopped.
2017-07-31 08:36:45 | DEBUG | PlexPy APIv2 :: Cleaned kwargs: {}
2017-07-31 08:36:45 | DEBUG | PlexPy APIv2 :: API called with kwargs: {'cmd': u'get_activity', 'apikey': u'********39'}
2017-07-31 08:36:34 | DEBUG | PlexPy APIv2 :: Cleaned kwargs: {}
2017-07-31 08:36:34 | DEBUG | PlexPy APIv2 :: API called with kwargs: {'cmd': u'get_activity', 'apikey': u'********39'}

2017-07-31 08:34:57 | DEBUG | PlexPy Notifiers :: Executing script in a new thread.
2017-07-31 08:34:57 | DEBUG | PlexPy Notifiers :: Full script is: ['python', 'C:\\JBOPS\\killstream\\create_wait_kill_trans.py', '1']
2017-07-31 08:34:57 | DEBUG | PlexPy Notifiers :: Trying to run notify script, action: pause, arguments: [u'1']
2017-07-31 08:34:56 | DEBUG | PlexPy ActivityHandler :: Session 1 has been paused.
2017-07-31 08:34:44 | DEBUG | PlexPy APIv2 :: Cleaned kwargs: {}


```

**Comment by seanvree** [comment]
@blacktwin  - that's what I've got : " {session_key} " right?





![plexpykillargs](https://user-images.githubusercontent.com/8906637/28788874-890011a2-75d7-11e7-820e-f73bfd465d05.png)

**Comment by blacktwin** [comment]
@seanvree I'll look into it again later. Weird that it's pulling the incorrect value... the (-com-plexapp-android) looks like a device id or something. Could you add 
```python
import json
print(json.dumps(response, indent=4, sort_keys=True))
```
[into line 134](https://github.com/blacktwin/JBOPS/blob/master/killstream/create_wait_kill_trans.py#L134). Can you PM me the output. I'd like to see why it's pulling that value.

**Comment by seanvree** [comment]
@blacktwin  - that's what I've got : " {session_key} " right?

Screenshot:

http://imgur.com/1dAjYVs

**Comment by seanvree** [comment]
@blacktwin 

I'm no coder, so go easy, 

```

    fileDir = fileDir = os.path.dirname(os.path.realpath(__file__))
	import json
	print(json.dumps(response, indent=4, sort_keys=True))

```

is that right?

I executed from a CMD Prompt and got this:

```

C:\WINDOWS\system32>cd C:\JBOPS\killstream

C:\JBOPS\killstream>python create_wait_kill_trans.py
  File "create_wait_kill_trans.py", line 135
    import json
    ^
IndentationError: unexpected indent

C:\JBOPS\killstream>

```

**Comment by blacktwin** [comment]
Try [this](https://github.com/blacktwin/JBOPS/blob/daf9be07d598b2edb7aacfe4ac10e8d0afb75afa/killstream/create_wait_kill_trans.py).

**Comment by seanvree** [comment]
@blacktwin  - 

Not sure where to PM you at, Tried discord, but it's an error page, So, I shot you on reddit. 

So the output looks good, however, that's not the  same device that we were trying earlier, if you need me to do that I can.

**Comment by blacktwin** [comment]
Issue closed with [update](https://github.com/blacktwin/JBOPS/commit/779ad0b14fe7e5907987af3c33a963bc1f488584)

**Comment by seanvree** [comment]
Thanks brotha!

**Comment by solidragon** [comment]
hello, someone can help me I can not run the scrypts, I have pip installer and update as well as plexpi but I still have errors in the script. the scripts is not in the plexpy folder i'm on qnap, and i have tautulli plexpy update, here are the errors.

2018-08-07 15:03:52 | DEBUG | Tautulli Notifiers :: Full script is: ['python', u'/share/CACHEDEV1_DATA/Plex/Plex Scripts/Kills stream/kill_stream.py', 'u--jbop,', 'uallStreams,', 'u--userId,', 'u12839010,', 'u--notify,', 'u1,', 'u--killMessage,', 'uHey Bob, we need to talk!']
-- | -- | --
2018-08-07 15:03:52 | DEBUG | Tautulli Notifiers :: Executing script in a new thread.
2018-08-07 15:03:56 | ERROR | Tautulli Notifiers :: Script error:         File "/share/CACHEDEV1_DATA/Plex/Plex Scripts/Kills stream/kill_stream.py", line 1             import requests             ^     IndentationError: unexpected indent

thank you
