### ISSUE TITLE
wait_kill_pause_notify_main.py IndexError: list index out of range

### ISSUE THREAD

**Issue by dotzeno** [blacktwin/JBOPS#63]
Hi,
I'm using Tautulli version 2.0.28.
Script notification settings are set to the following:
Configuration: Script File -> .\wait_kill_pause_notify_main.py
Triggers: Notify on Playback Pause
Conditions: None
Arguments: Playback Pause -> {session_key}

wait_kill_pause_notify_sub.py has been placed in the same directory as wait_kill_pause_notify_main.py.

I keep getting the following two log entries (removed html tags and replaced sessionid with placeholder)

```
2018-04-03 16:05:30 | ERROR | Tautulli Notifiers :: Script error:     Traceback (most recent call last):         File "D:\Tautulli\scripts\wait_kill_pause_notify_main.py", line 59, in <module>             sessionKey = sys.argv[1]     IndexError: list index out of range
-- | -- | --
2018-04-03 16:05:28 | DEBUG | Tautulli Notifiers :: Script returned:     Executing sub script.     Sub script initiating kill.     Successfully sent Tautulli notification.Error: (401) unauthorized; http://localhost:32400/status/sessions/terminate?sessionId=[SESSIONID_PLACEHOLDER]&reason=This+stream+has+ended+due+to+being+paused. Unauthorized401 Unauthorized
```
Any assistance would be appreciate, thanks.

**Comment by blacktwin** [comment]
Show more logs. The IndexError would suggest that your `{session_key}` is not set.

**Comment by dotzeno** [comment]
Thanks for the feedback.
Although, I'm not sure how to go about setting it. Any advice?

Here's some more log entries:

Timestamp | Level | Message
-- | -- | --
2018-04-04 09:55:06 | ERROR | Tautulli Notifiers :: Script error:     Traceback (most recent call last):         File "D:\Tautulli\scripts\wait_kill_pause_notify_main.py", line 59, in <module>             sessionKey = sys.argv[1]     IndexError: list index out of range
2018-04-04 09:55:05 | DEBUG | Tautulli Notifiers :: Script returned:     Executing sub script.     Sub script initiating kill.     Successfully sent Tautulli notification.Error: (401) unauthorized; http://localhost:32400/status/sessions/terminate?sessionId=[Sessionid_Placeholder]&reason=This+stream+has+ended+due+to+being+paused. 401 Unauthorized
2018-04-04 09:55:05 | DEBUG | Tautulli Notifiers :: Executing script in a new thread.
2018-04-04 09:55:05 | DEBUG | Tautulli Notifiers :: Full script is: ['python', 'D:\\Tautulli\\scripts\\wait_kill_pause_notify_main.py']
2018-04-04 09:55:05 | DEBUG | Tautulli Notifiers :: Trying to run notify script, action: api, arguments: []
2018-04-04 09:55:05 | INFO | Tautulli NotificationHandler :: Preparing notifications for notifier_id 1.
2018-04-04 09:54:48 | WARNING | Tautulli Notifiers :: Script exceeded timeout limit of 30 seconds. Script killed.
2018-04-04 09:54:18 | DEBUG | Tautulli Notifiers :: Executing script in a new thread.
2018-04-04 09:54:18 | DEBUG | Tautulli Notifiers :: Full script is: ['python', 'D:\\Tautulli\\scripts\\wait_kill_pause_notify_main.py', '2']
2018-04-04 09:54:18 | DEBUG | Tautulli Notifiers :: Trying to run notify script, action: pause, arguments: [u'2']
2018-04-04 09:54:18 | INFO | Tautulli NotificationHandler :: Preparing notifications for notifier_id 1.
2018-04-04 09:54:18 | DEBUG | Tautulli ActivityHandler :: Session 2 paused.
2018-04-04 09:54:18 | DEBUG | Tautulli ActivityHandler :: Session 2 started by user 3978689 ([Userid_Placeholder]) with ratingKey 17446 ([Media_Placeholder).

**Comment by blacktwin** [comment]
Looks like it passed the argument correctly once.
```
2018-04-04 09:54:18 | DEBUG | Tautulli Notifiers :: Full script is: ['python', 'D:\\Tautulli\\scripts\\wait_kill_pause_notify_main.py', '2']
2018-04-04 09:54:18 | DEBUG | Tautulli Notifiers :: Trying to run notify script, action: pause, arguments: [u'2']
```
Looks like you changed something:
```
2018-04-04 09:55:05 | DEBUG | Tautulli Notifiers :: Full script is: ['python', 'D:\\Tautulli\\scripts\\wait_kill_pause_notify_main.py']
2018-04-04 09:55:05 | DEBUG | Tautulli Notifiers :: Trying to run notify script, action: api, arguments: []
```

**Comment by blacktwin** [comment]
@dotzeno I think you may have your notifier_id set to the wait_kill_pause_notify_main script. It should be set to a notification id that would be use to send out a message like email, discord, telegram, etc. Or none at all.

**Comment by dotzeno** [comment]
Thanks for the clarification and the information.
I have since changed the notifier_id to none but paused streams don't seem to be killed and I still get the 401 unauthorized log messages.

The log entries look like this now:

Timestamp | Level | Message  
-- | -- | --
2018-04-06 13:29:44 | DEBUG | Tautulli Notifiers :: Script returned:     Executing sub script.     Sub script initiating kill.     Error: (401) unauthorized; http://localhost:32400/status/sessions/terminate?sessionId=[SESSIONID_PLACEHOLDER]&reason=This+stream+has+ended+due+to+being+paused. Unauthorized 401 Unauthorized
2018-04-06 13:29:29 | WARNING | Tautulli Notifiers :: Script exceeded timeout limit of 30 seconds. Script killed.
2018-04-06 13:28:59 | DEBUG | Tautulli Notifiers :: Executing script in a new thread.
2018-04-06 13:28:59 | DEBUG | Tautulli Notifiers :: Full script is: ['python', 'D:\\Tautulli\\scripts\\wait_kill_pause_notify_main.py', '10']
2018-04-06 13:28:59 | DEBUG | Tautulli Notifiers :: Trying to run notify script, action: pause, arguments: [u'10']
2018-04-06 13:28:59 | INFO | Tautulli NotificationHandler :: Preparing notifications for notifier_id 1.
2018-04-06 13:28:59 | DEBUG | Tautulli ActivityHandler :: Session 10 paused.
2018-04-06 13:28:55 | DEBUG | Tautulli ActivityHandler :: Session 10 started by user 3978689 (dotzeno) with ratingKey 16349 ([MEDIA_PLACEHOLDER]).

**Comment by blacktwin** [comment]
Do you have Plex Pass?

**Comment by dotzeno** [comment]
I don't have a Plex Pass, is that the problem?

**Comment by blacktwin** [comment]
Yes. Plex Pass is needed to be able to kill streams. This is in the [readme ](https://github.com/blacktwin/JBOPS/blob/master/killstream/readme.md)in the killstream section.

**Comment by dotzeno** [comment]
Oh... my apologies. Should have read the readme first.
Thanks for taking the time to help me!
