### ISSUE TITLE
plex_netflix_check.py fail when Movie title is only numbers

### ISSUE THREAD

**Issue by psike** [blacktwin/JBOPS#65]
Movie name: 1922
Script trying to do lower function but fail because it is an integer.

Search for '1922' found 32 matches.
Traceback (most recent call last):
  File "plex_netflix_check.py", line 227, in <module>
    main()
  File "plex_netflix_check.py", line 224, in main
    plex_library_search(opts.library[0], opts.site, opts.episodes, opts.search_limit)
  File "plex_netflix_check.py", line 174, in plex_library_search
    if instantwatch_search(title.title, title.type, site, search_limit) > 0:
  File "plex_netflix_check.py", line 112, in instantwatch_search
    if data['a']['$'].lower().startswith(name.lower()):
AttributeError: 'int' object has no attribute 'lower'

**Comment by blacktwin** [comment]
Updated. Try again please.

**Comment by psike** [comment]
Fixed, Thanks.
