### ISSUE TITLE
Kill_stream.py not working

### ISSUE THREAD

**Issue by Jakefr0mSt4t3F4rm** [blacktwin/JBOPS#98]
```

Tautulli Notifiers :: Script error: 
    Traceback (most recent call last): 
        File "/var/lib/tautulli/script/kill_stream.py", line 575, in <module> 
            opts = parser.parse_args() 
        File "/usr/lib/python3.7/argparse.py", line 1749, in parse_args 
            args, argv = self.parse_known_args(args, namespace) 
        File "/usr/lib/python3.7/argparse.py", line 1781, in parse_known_args 
            namespace, args = self._parse_known_args(args, namespace) 
        File "/usr/lib/python3.7/argparse.py", line 1987, in _parse_known_args 
            start_index = consume_optional(start_index) 
        File "/usr/lib/python3.7/argparse.py", line 1927, in consume_optional 
            take_action(action, args, option_string) 
        File "/usr/lib/python3.7/argparse.py", line 1839, in take_action 
            argument_values = self._get_values(action, argument_strings) 
        File "/usr/lib/python3.7/argparse.py", line 2369, in _get_values 
            value = self._get_value(action, arg_string) 
        File "/usr/lib/python3.7/argparse.py", line 2402, in _get_value 
            result = type_func(arg_string) 
        File "/var/lib/tautulli/script/kill_stream.py", line 100, in arg_decoding 
            return arg.decode(TAUTULLI_ENCODING).encode('UTF-8') 
    AttributeError: 'str' object has no attribute 'decode'
```

[Screenshot since I can't get the formatting right](https://imgur.com/a/iPum5lU)

The above error is all I am able to get. Plus, the second condition which I have set to `Library name` `Contains` `4K` never triggers (Tautulli always sees that condition as false) Even though "4K" is indeed in the library name.

**Comment by Arcanemagus** [comment]
It looks like you are trying to run this through Python 3. Currently `kill_stream.py` is written for Python 2 (as is Tautulli).

You can read [this FAQ entry](https://github.com/Tautulli/Tautulli-Wiki/wiki/Frequently-Asked-Questions#notifications-override-python) for how to override the version of Python used, you _likely_ have a `python2` available to use there.

**Comment by Jakefr0mSt4t3F4rm** [comment]
Well when I try to run it in Python2 I get this, which I figured meant it was written for Python3. Yet no matter what I do it seems to error out.
[Screenshot since I can't Markdown today](https://imgur.com/a/isMUtko)

**Comment by Arcanemagus** [comment]
> /usr/lib/python3.7/argparse.py

Your initial run was already through Python 3, was your next one following the FAQ? Maybe that cleared up some conflicting stuff?

**Comment by Jakefr0mSt4t3F4rm** [comment]
I am 100% lost for an answer. I even fired up a VM, installed Tautulli, and tested the script in a clean environment and still, no matter if I use Python2, Python3, etc the only result is one of the two errors I have encountered. Either:

```

Tautulli Notifiers :: Script error: 
Fatal Python error: initfsencoding: Unable to get the locale encoding
File "/usr/lib/python2.7/encodings/__init__.py", line 123
raise CodecRegistryError,\ 
                                           ^
SyntaxError: invalid syntax 
Current thread 0x0000294f46bc5600 (most recent call first):
```
Running under Python2.

Or:

```

Tautulli Notifiers :: Script error: 
    Traceback (most recent call last): 
        File "/var/lib/tautulli/script/kill_stream.py", line 575, in <module> 
            opts = parser.parse_args() 
        File "/usr/lib/python3.7/argparse.py", line 1749, in parse_args 
            args, argv = self.parse_known_args(args, namespace) 
        File "/usr/lib/python3.7/argparse.py", line 1781, in parse_known_args 
            namespace, args = self._parse_known_args(args, namespace) 
        File "/usr/lib/python3.7/argparse.py", line 1987, in _parse_known_args 
            start_index = consume_optional(start_index) 
        File "/usr/lib/python3.7/argparse.py", line 1927, in consume_optional 
            take_action(action, args, option_string) 
        File "/usr/lib/python3.7/argparse.py", line 1839, in take_action 
            argument_values = self._get_values(action, argument_strings) 
        File "/usr/lib/python3.7/argparse.py", line 2369, in _get_values 
            value = self._get_value(action, arg_string) 
        File "/usr/lib/python3.7/argparse.py", line 2402, in _get_value 
            result = type_func(arg_string) 
        File "/var/lib/tautulli/script/kill_stream.py", line 100, in arg_decoding 
            return arg.decode(TAUTULLI_ENCODING).encode('UTF-8') 
    AttributeError: 'str' object has no attribute 'decode'
```
under Python3.

**Comment by Jakefr0mSt4t3F4rm** [comment]
I seem to have gotten the script working. I just added `nopythonpath python2` to the script arguments, odd since Tautulli uses python2 already so presumably any script run under the Tautulli user would also just use python2.

**Comment by Jakefr0mSt4t3F4rm** [comment]
Thanks for the help. Your comment about the FAQ prompted me to reread it which led me to testing what I did.
